package:
  name: bash
  version: 5.2.21
  epoch: 5
  description: "GNU bourne again shell"
  copyright:
    - license: GPL-3.0-or-later

# The bash git repository only tags using major.minor version numbers
var-transforms:
  - from: ${{package.version}}
    match: (\d+\.\d+).*
    replace: $1
    to: mangled-package-version

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - ncurses-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://git.savannah.gnu.org/git/bash.git
      tag: bash-${{vars.mangled-package-version}}
      expected-commit: 74091dd4e8086db518b30df7f222691524469998

  - runs: |
      ./configure \
        --host=${{host.triplet.gnu}} \
        --target=${{host.triplet.gnu}} \
        --prefix=/usr \
        --bindir=/bin \
        --sysconfdir=/etc \
        --without-libidn \
        --with-ssl=openssl \
        --disable-nls \
        --enable-readline \
        --without-bash-malloc \
        --with-curses

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: bash-binsh
    dependencies:
      provider-priority: 60
      runtime:
        - bash
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/bin
          ln -s bash "${{targets.subpkgdir}}"/bin/sh
    test:
      pipeline:
        - runs: |
            [ /bin/sh -ef /bin/bash ] || { echo "/bin/sh is not same as /bin/bash"; exit 1; }

  - name: "bash-doc"
    description: "bash documentation"
    pipeline:
      - uses: split/manpages
      - uses: split/infodir
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share
          mv "${{targets.destdir}}"/usr/share/doc "${{targets.subpkgdir}}"/usr/share/

  - name: "bash-dev"
    description: "bash development headers"
    pipeline:
      - uses: split/dev
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/bin
          mv "${{targets.destdir}}"/bin/bashbug "${{targets.subpkgdir}}"/bin/

  - name: "bash-builtins"
    description: "bash loadable builtins"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib
          mv "${{targets.destdir}}/usr/lib/bash" ${{targets.subpkgdir}}/usr/lib/

update:
  enabled: true
  release-monitor:
    identifier: 166

test:
  pipeline:
    - runs: |
        /bin/bash --version || exit 1
    - runs: |
        /bin/bash -c "echo 'hello world'" || exit 1
