package:
  name: boring-registry
  version: 0.15.1
  epoch: 0
  description: Terraform Provider and Module Registry
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 7546675385385eb7d6ee6edf69fbbb3de8d85751
      repository: https://github.com/TierMobility/boring-registry
      tag: v${{package.version}}

  - uses: go/build
    with:
      ldflags: |
        -s -w
        -X github.com/TierMobility/boring-registry/version.Version="${{package.version}}"
        -X github.com/TierMobility/boring-registry/version.Commit="$(git rev-parse --verify HEAD --short)"
        -X github.com/TierMobility/boring-registry/version.Date="$(date -u +'%FT%T%z')"
      output: boring-registry
      packages: .

  - uses: strip

update:
  enabled: true
  manual: false
  github:
    identifier: TierMobility/boring-registry
    strip-prefix: v
