package:
  name: c-ares
  version: 1.32.3
  epoch: 0
  description: "an asynchronous DNS resolution library"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libtool
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/c-ares/c-ares.git
      tag: v${{package.version}}
      expected-commit: 5899dea2b1f8e78f311aaed7db98b82b5537c9f9

  - runs: |
      autoreconf -vfi

  - uses: autoconf/configure
    with:
      # Enabling tests requires a gmock dependency. We have that packaged, but it introduces a dependency cycle.
      opts: --enable-shared --enable-tests=no

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "c-ares-dev"
    description: "headers for c-ares"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libev

  - name: "c-ares-doc"
    description: "c-ares documentation"
    pipeline:
      - uses: split/manpages

update:
  enabled: true
  github:
    identifier: c-ares/c-ares
    tag-filter-prefix: v
    strip-prefix: v
