package:
  name: cadvisor
  version: 0.50.0
  epoch: 0
  description: Analyzes resource usage and performance characteristics of running containers.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/google/cadvisor
      tag: v${{package.version}}
      expected-commit: 256737f329f705a0a8a95578efb9b36a5401d36d

  - runs: |
      ./build/build.sh

  - runs: |
      install -Dm755 _output/cadvisor "${{targets.destdir}}"/usr/bin/cadvisor

  - uses: strip

update:
  enabled: true
  github:
    identifier: google/cadvisor
    strip-prefix: v
    tag-filter: v
    use-tag: true
