package:
  name: cargobump
  version: 0.0.2
  epoch: 0
  description: Rust tool to declaratively bump dependencies using cargo
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hectorj2f/cargobump.git
      tag: v${{package.version}}
      expected-commit: a73f667bcda95c3561668824fd9005842497b989

  - uses: go/build
    with:
      packages: .
      output: cargobump

  - uses: strip

update:
  enabled: true
  github:
    identifier: chainguard-dev/cargobump
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - runs: |
        cargobump version
