package:
  name: cluster-autoscaler-1.30
  version: 1.30.2
  epoch: 1
  description: Autoscaling components for Kubernetes
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - cluster-autoscaler=${{package.full-version}}

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes/autoscaler
      tag: cluster-autoscaler-${{package.version}}
      expected-commit: a0fce3ce1c7961911ec1f77fcf4c894b0eb18080

  - uses: go/bump
    with:
      deps: go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.46.0 go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.46.0 go.opentelemetry.io/otel/sdk@v1.21.0 go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc@v1.21.0 k8s.io/kubernetes@v1.30.3
      replaces: k8s.io/cloud-provider-aws=k8s.io/cloud-provider-aws@v1.29.2
      modroot: cluster-autoscaler

  - uses: go/build
    with:
      modroot: cluster-autoscaler
      packages: .
      output: cluster-autoscaler
      ldflags: -s -w
      vendor: true

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}
          # The upstream helm chart assumes the binary is in /.
          ln -sf /usr/bin/cluster-autoscaler ${{targets.subpkgdir}}/cluster-autoscaler
    dependencies:
      provides:
        - cluster-autoscaler-compat=${{package.full-version}}

update:
  enabled: true
  github:
    identifier: kubernetes/autoscaler
    strip-prefix: cluster-autoscaler-
    use-tag: true
    # There are other tags like "cluster-autoscaler-chart-FOO"
    tag-filter: cluster-autoscaler-1.30.
