package:
  name: composer
  version: 2.7.7
  epoch: 0
  description: "the PHP package manager"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - git
      - php

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    with:
      uri: https://getcomposer.org/download/${{package.version}}/composer.phar
      expected-sha256: 06e4c4bc6d32b8975174f4f4a0a93476d8907da92a1484c5a8ef138897a760e1
      extract: "false"
      delete: "false"

  - name: Install Composer
    runs: |
      EXEC_DIR="${{targets.destdir}}/usr/bin"
      mkdir -p "${EXEC_DIR}"
      mv composer.phar "${EXEC_DIR}/composer"
      chmod +x "${EXEC_DIR}/composer"

update:
  enabled: true
  github:
    identifier: composer/composer
