package:
  name: configmap-reload
  version: 0.13.1
  epoch: 1
  description: Simple binary to trigger a reload when a Kubernetes ConfigMap is updated
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jimmidyson/configmap-reload
      expected-commit: 5a00f12b55609ae247848595ecd994d78c7e99aa
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: configmap-reload.go
      output: configmap-reload
      ldflags: -s -w -extldflags '-static'

  - uses: strip

update:
  enabled: true
  github:
    identifier: jimmidyson/configmap-reload
    strip-prefix: v
    tag-filter: v
    use-tag: true
