package:
  name: cortex
  version: 1.16.0
  epoch: 2
  description:
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cortexproject/cortex
      tag: v${{package.version}}
      expected-commit: 279ed566d01228e4b95fd628a3d79dd3ca95c9d8

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.58.3 golang.org/x/crypto@v0.17.0

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      go build -ldflags \
        "-s -w \
        -X main.Branch=$(git rev-parse --abbrev-ref HEAD) \
        -X main.Revision=$(git rev-parse --short HEAD) \
        -X main.Version=$(cat ./VERSION)" \
        -o ${{targets.destdir}}/usr/bin/cortex ./cmd/cortex

  - uses: strip

update:
  enabled: true
  github:
    identifier: cortexproject/cortex
    strip-prefix: v
