package:
  name: croc
  version: 10.0.11
  epoch: 0
  description: Easily and securely send things from one computer to another
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ca-certificates-bundle
      - git

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/schollz/croc
      expected-commit: bf26db019cbe2862aef963cd0a32f5f2d62d15d4
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: .
      output: croc
      ldflags: -s -w

  - uses: strip

update:
  enabled: true
  github:
    identifier: schollz/croc
    strip-prefix: v
