package:
  name: crossplane
  version: 1.14.5
  epoch: 1
  description: Cloud Native Control Planes
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: e4a418081e6fec505fe47b6e7c20ac689faa973e
      repository: https://github.com/crossplane/crossplane
      tag: v${{package.version}}

  - runs: |
      mkdir -p ${{targets.destdir}}/crds
      cp cluster/crds/* ${{targets.destdir}}/crds

      mkdir -p ${{targets.destdir}}/webhookconfigurations
      cp cluster/webhookconfigurations/* ${{targets.destdir}}/webhookconfigurations

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0

  - uses: go/build
    with:
      ldflags: -w
      output: crossplane
      packages: ./cmd/crossplane

  - uses: strip

subpackages:
  - name: crossplane-crank
    pipeline:
      - uses: go/bump
        with:
          deps: github.com/go-git/go-git/v5@v5.11.0

      - uses: go/build
        with:
          ldflags: -w
          output: crank
          packages: ./cmd/crank
          subpackage: "true"
      - uses: strip

update:
  enabled: true
  github:
    identifier: crossplane/crossplane
    strip-prefix: v
