package:
  name: ctop
  version: 0.7.7
  epoch: 13
  description: Top-like interface for container metrics
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 11a1cb10f416b4ca5e36c22c1acc2d11dbb24fb4
      repository: https://github.com/bcicen/ctop
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/sys@v0.0.0-20220412211240-33da011f77ad github.com/docker/docker@v24.0.9 github.com/containerd/containerd@v1.6.26 github.com/cyphar/filepath-securejoin@v0.2.4 github.com/opencontainers/image-spec@v1.0.2 google.golang.org/protobuf@v1.33.0 github.com/gogo/protobuf@v1.3.2
      replaces: github.com/containerd/containerd=github.com/containerd/containerd@v1.6.26 github.com/fsouza/go-dockerclient=github.com/fsouza/go-dockerclient@v1.9.5 github.com/opencontainers/runc=github.com/opencontainers/runc@v1.0.2
      show-diff: true

  - runs: |
      cat go.mod
      make build
      install -Dm755 ctop "${{targets.destdir}}"/usr/bin/ctop

  - uses: strip

update:
  enabled: true
  github:
    identifier: bcicen/ctop
    strip-prefix: v
