package:
  name: delve
  version: 1.23.0
  epoch: 0
  description: Delve is a debugger for the Go programming language.
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/go-delve/delve
      tag: v${{package.version}}
      expected-commit: 56e9b85f40ccd5ea92186ac54dba79a2f55d2197

  - runs: |
      make build
      mkdir -p ${{targets.destdir}}/usr/bin/
      mv dlv ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: go-delve/delve
    strip-prefix: v
