package:
  name: dgraph
  version: 24.0.1
  epoch: 0
  description: A distributed graph database
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - curl
      - go
      - jemalloc-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dgraph-io/dgraph
      tag: v${{package.version}}
      expected-commit: ee57c5e98560ff8005c15def550494f0f26fa63a

  # this patch is to prevent draph to install jemalloc and use the system one
  - uses: patch
    with:
      patches: |
        find-jemalloc.patch
        change_jose.patch

  - runs: |
      make install_oss
      mkdir -p ${{targets.destdir}}/usr/bin
      mv $(go env GOPATH)/bin/dgraph ${{targets.destdir}}/usr/bin

  - uses: strip

update:
  enabled: true
  github:
    identifier: dgraph-io/dgraph
    strip-prefix: v
    tag-filter: v
