# rabbitmq-server package depends on this version of elixir.
package:
  name: elixir-1.15
  version: 1.15.8
  epoch: 1
  description: General-purpose programming language and runtime environment
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - erlang-26
    provides:
      - elixir=${{package.full-version}}

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - erlang-26
      - erlang-26-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 09e697ab13fc60f27adaba9b71f8793105acd4320a89b16be0ceb4a13426d779
      uri: https://github.com/elixir-lang/elixir/archive/refs/tags/v${{package.version}}.tar.gz

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  github:
    identifier: elixir-lang/elixir
    strip-prefix: v
    tag-filter-prefix: v1.15
