package:
  name: emacs
  version: "29.4"
  epoch: 1
  description: "An extensible, customizable, free/libre text editor"
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - gawk
      - libtool
      - libxml2-dev
      - ncurses-dev
      - posix-libc-utils
      - texinfo
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/emacs-mirror/emacs
      tag: emacs-${{package.version}}
      expected-commit: 6a299b3caceb2c73b932ba73849738faa8c5d975

  - runs: autoreconf -vif

  - uses: autoconf/configure
    with:
      opts: |
        --with-x=no \
        --with-gnutls=ifavailable \
        --with-mailutils=no \
        --with-pop=no

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "emacs-doc"
    pipeline:
      - uses: split/manpages
      - uses: split/infodir

update:
  enabled: true
  github:
    identifier: emacs-mirror/emacs
    strip-prefix: emacs-
    use-tag: true
    tag-filter: emacs-
