package:
  name: envoy-ratelimit
  # This project doesn't do releases and everything is commit based.
  # This corresponds to commit f3b67307a53c3979783bef4de8bfa655167b0807
  version: 0.0_git20240220
  epoch: 13
  description: Go/gRPC service designed to enable generic rate limit scenarios from different types of applications.
  copyright:
    - license: Apache-2.0

vars:
  commit: f3b67307a53c3979783bef4de8bfa655167b0807

pipeline:
  - runs: |
      git clone https://github.com/envoyproxy/ratelimit ratelimit/
      cd ratelimit/
      git checkout ${{vars.commit}}

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0 golang.org/x/net@v0.23.0
      modroot: ratelimit

  - uses: go/build
    with:
      modroot: ratelimit
      output: ratelimit
      packages: ./src/service_cmd

test:
  environment:
    contents:
      packages:
        - go
  pipeline:
    - runs: go version -m /usr/bin/ratelimit | grep "vcs.revision=${{vars.commit}}$"

subpackages:
  - name: envoy-ratelimit-compat
    pipeline:
      - runs: |
          # The helm chart expects the ratelimit binary to be in /bin instead of /usr/bin
          mkdir -p "${{targets.subpkgdir}}"/bin
          ln -sf /usr/bin/ratelimit ${{targets.subpkgdir}}/bin/ratelimit
    description: Compatibility package to place binaries in the location expected by upstream helm charts

update:
  enabled: false
