package:
  name: esbuild
  version: 0.23.0
  epoch: 1
  description: An extremely fast bundler for the web
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - nodejs

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/evanw/esbuild
      tag: v${{package.version}}
      expected-commit: 9d506806bdd963b02b3d6edf45e717e03dcba785

  - runs: |
      node scripts/esbuild.js --update-version-go

  - uses: go/build
    with:
      packages: ./cmd/esbuild
      output: esbuild

update:
  enabled: true
  github:
    identifier: evanw/esbuild
    strip-prefix: v
