#nolint:valid-pipeline-git-checkout-commit,valid-pipeline-git-checkout-tag
package:
  name: fluent-plugin-tag-normaliser
  version: 0.1.2_git20230928
  epoch: 3
  description: Tag-normaliser is a `fluentd` plugin to help re-tag logs with Kubernetes metadata. It uses special placeholders to change tag.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ruby3.2-fluentd

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

pipeline:
  - runs: |
      git clone https://github.com/kube-logging/fluent-plugin-tag-normaliser
      cd fluent-plugin-tag-normaliser
      git checkout 977a7a0de97db777d83f0db660a3789dcd83a5d4

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}
      dir: fluent-plugin-tag-normaliser

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      dir: fluent-plugin-tag-normaliser
      version: 0.1.2 # hard coded as no tags or releases

  - uses: ruby/clean

vars:
  gem: fluent-plugin-tag-normaliser

update:
  enabled: false
