package:
  name: flyte
  version: 1.12.0
  epoch: 4
  description: Scalable and flexible workflow orchestration platform that seamlessly unifies data, ML and analytics stacks.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/flyteorg/flyte
      tag: v${{package.version}}
      expected-commit: bd3ed0d2684bddbc8fad1c26d4bc39a86e91077f

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.23.0 github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.6.0

  - uses: go/build
    with:
      modroot: .
      packages: ./cmd
      output: flyte
      ldflags: -s -w

  - uses: strip

update:
  enabled: true
  github:
    identifier: flyteorg/flyte
    strip-prefix: v

test:
  pipeline:
    - runs: |
        flyte --help
