package:
  name: fribidi
  version: 1.0.15
  epoch: 1
  description: Free Implementation of the Unicode Bidirectional Algorithm
  copyright:
    - license: LGPL-2.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - meson

pipeline:
  - uses: fetch
    with:
      expected-sha256: 0bbc7ff633bfa208ae32d7e369cf5a7d20d5d2557a0b067c9aa98bcbf9967587
      uri: https://github.com/fribidi/fribidi/releases/download/v${{package.version}}/fribidi-${{package.version}}.tar.xz

  - uses: meson/configure
    with:
      opts: -Ddefault_library=both

  - uses: meson/compile

  - uses: meson/install

  - uses: strip

subpackages:
  - name: fribidi-doc
    pipeline:
      - uses: split/manpages
    description: fribidi manpages

  - name: fribidi-static
    pipeline:
      - uses: split/static
    description: fribidi static

  - name: fribidi-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - fribidi
    description: fribidi dev

update:
  enabled: true
  github:
    identifier: fribidi/fribidi
    strip-prefix: v
    use-tag: true
    tag-filter: v
