package:
  name: geos
  version: 3.12.2
  epoch: 0
  description: GEOS is a library providing OpenGIS and JTS spatial operations in C++.
  copyright:
    - license: LGPL-2.1-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - samurai

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/libgeos/geos
      tag: ${{package.version}}
      expected-commit: b74fefb7be4ba6c833760106f95f0f495b832c43

  - uses: cmake/configure

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: geos-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - geos
    description: geos dev

update:
  enabled: true
  github:
    identifier: libgeos/geos
