package:
  name: gitness
  version: 3.0.0_beta4
  epoch: 2
  description: Gitness is an Open Source developer platform with Source Control management, Continuous Integration and Continuous Delivery.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - nodejs
      - protobuf
      - protoc
      - protoc-gen-go
      - protoc-gen-go-grpc
      - yarn

var-transforms:
  - from: ${{package.version}}
    match: _beta
    replace: -beta.
    to: mangled-package-version

pipeline:
  - uses: git-checkout
    with:
      # Hack until they cut a release
      repository: https://github.com/harness/gitness/
      expected-commit: 93c5cfd36e3739e12564416d2def52bca2777af1
      tag: v${{vars.mangled-package-version}}

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.17.0 google.golang.org/grpc@v1.56.3 golang.org/x/crypto@v0.17.0 github.com/containerd/containerd@v1.7.11 github.com/sercand/kuberesolver/v5@v5.1.1

  - runs: |
      cd web
      yarn && yarn build && yarn cache clean
      cd ..

      echo "githiness "
      echo $GOPATH
      echo $GOBIN
      export GOBIN="${{targets.destdir}}"/usr/bin
      echo $GOBIN

      make dep
      make tools
      make build

      mkdir -p ${{targets.destdir}}/usr/bin
      mv gitness ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: harness/gitness
    strip-prefix: v
