package:
  name: gitness
  version: 3.0.0_beta2
  epoch: 3
  description: Gitness is an Open Source developer platform with Source Control management, Continuous Integration and Continuous Delivery.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - nodejs
      - protobuf
      - protoc
      - protoc-gen-go
      - protoc-gen-go-grpc
      - yarn

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 1c762c6802b391ef2f3346886629bb0c1d514e24
      repository: https://github.com/harness/gitness/
      tag: v${{vars.mangled-package-version}}

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.17.0 google.golang.org/grpc@v1.56.3 golang.org/x/crypto@v0.17.0 github.com/containerd/containerd@v1.7.11 github.com/sercand/kuberesolver/v5@v5.1.1 code.gitea.io/gitea@v1.19.4 github.com/go-git/go-git/v5@v5.11.0

  - runs: |
      cd web
      yarn && yarn build && yarn cache clean
      cd ..

      make dep
      make tools
      make build

      mkdir -p ${{targets.destdir}}/usr/bin
      mv gitness ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  manual: false
  github:
    identifier: harness/gitness
    strip-prefix: v

var-transforms:
  - from: ${{package.version}}
    match: _beta
    replace: -beta.
    to: mangled-package-version
