package:
  name: grafana-alloy
  version: 1.2.1
  epoch: 2
  description: OpenTelemetry Collector distribution with programmable pipelines
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/grafana/alloy
      tag: v${{package.version}}
      expected-commit: e83e8af406b19c11b102b76f21142f7561a77036

  - uses: go/bump
    with:
      deps: github.com/hashicorp/go-retryablehttp@v0.7.7 google.golang.org/grpc@v1.64.1

  - uses: go/build
    with:
      packages: .
      output: grafana-alloy
      ldflags: -s -w

  - uses: strip

  - name: Setup default config files
    runs: |
      mkdir -p ${{targets.destdir}}/etc/alloy/
      install -m644 -D packaging/config.alloy ${{targets.destdir}}/etc/alloy/

subpackages:
  - name: "${{package.name}}-compat"
    # https://github.com/grafana/alloy/blob/61225a67c0e7bdea2d348c0ce884ed713e5f8740/Dockerfile#L61
    description: "Compatibility package to place binaries in the location expected by upstream Dockerfile"
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}/bin"
          ln -sf /usr/bin/alloy ${{targets.contextdir}}/bin/alloy

test:
  pipeline:
    - runs: |
        /usr/bin/grafana-alloy --version

update:
  enabled: true
  ignore-regex-patterns:
    - -rc
  github:
    identifier: grafana/alloy
    strip-prefix: v
    use-tag: true
    tag-filter-prefix: v
