package:
  name: grpc-health-probe
  version: 0.4.30
  # bump to epoch 1 when 0.4.29 is released
  epoch: 0
  description: A command-line tool to perform health-checks for gRPC applications in Kubernetes and elsewhere
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/grpc-ecosystem/grpc-health-probe
      tag: v${{package.version}}
      expected-commit: f9136b23d79b9fbd43e4538c55b5276cb1b79b8b

  - uses: go/build
    with:
      packages: .
      output: grpc-health-probe
      ldflags: -X main.versionTag=v${{package.version}}

  - uses: strip

subpackages:
  - name: grpc-health-probe-compat
    pipeline:
      - runs: |
          # Symlink the binary from usr/bin to /bin
          mkdir -p "${{targets.subpkgdir}}"/bin
          ln -sf /usr/bin/grpc-health-probe ${{targets.subpkgdir}}/bin/grpc-health-probe
    dependencies:
      runtime:
        - grpc-health-probe

update:
  enabled: true
  github:
    identifier: grpc-ecosystem/grpc-health-probe
    strip-prefix: v
    use-tag: true
