package:
  name: haproxy-3.0
  version: 3.0.2
  epoch: 0
  description: "A TCP/HTTP reverse proxy for high availability environments"
  copyright:
    - license: GPL-2.0-or-later
  dependencies:
    runtime:
      - libgcc
    provides:
      - haproxy=${{package.full-version}}

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - libcap-utils
      - linux-headers
      - lua5.3-dev
      - openssl-dev
      - pcre2-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://git.haproxy.org/git/haproxy-3.0.git/
      tag: v${{package.version}}
      expected-commit: a45a8e6235853e787e59b13f07355f4729ae3c8e
      depth: "-1"

  - uses: autoconf/make
    with:
      opts: |
        TARGET=linux-glibc \
        USE_THREAD=1 \
        USE_PCRE2=1 \
        USE_PCRE2_JIT=1 \
        USE_OPENSSL=1 \
        USE_LUA=1 \
        USE_NS=1 \
        USE_PROMEX=1 \
        LUA_LIB=/usr/lib/lua5.3 \
        LUA_INC=/usr/include/lua5.3 \
        USE_GETADDRINFO=1

  - runs: |
      make install DESTDIR="${{targets.destdir}}" PREFIX=/usr DOCDIR=/usr/share/doc/haproxy
      install -d "${{targets.destdir}}"/var/lib/haproxy

  - uses: strip

  # This MUST run after strip, which strips capabilities too!
  - runs: setcap cap_net_bind_service=+eip "${{targets.destdir}}/usr/sbin/haproxy"

subpackages:
  - name: "${{package.name}}-doc"
    description: "haproxy documentation"
    pipeline:
      - uses: split/manpages
    dependencies:
      provides:
        - haproxy-doc=${{package.full-version}}

  - name: ${{package.name}}-oci-entrypoint
    description: Entrypoint for using HAProxy in OCI containers
    dependencies:
      runtime:
        - busybox
        - posix-libc-utils # `getent` is required for certain helm chart startups
      provides:
        - haproxy-oci-entrypoint=${{package.full-version}}
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/local/bin/
          cp docker-entrypoint.sh ${{targets.subpkgdir}}/usr/local/bin/
          chmod +x ${{targets.subpkgdir}}/usr/local/bin/docker-entrypoint.sh

update:
  enabled: false
  release-monitor:
    identifier: 1298
