package:
  name: hcloud
  version: 1.46.0
  epoch: 0
  description: A command-line interface for Hetzner Cloud
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hetznercloud/cli
      tag: v${{package.version}}
      expected-commit: 05e65b9feff2f9102d44577df6027f677b074559

  - uses: go/build
    with:
      packages: ./cmd/hcloud/main.go
      ldflags: |
        -s -w
        -X main.version=internal/version.version=${{package.version}}
      output: hcloud

  - uses: strip

update:
  enabled: true
  github:
    identifier: hetznercloud/cli
    strip-prefix: v

test:
  pipeline:
    - runs: |
        hcloud version
