package:
  name: imath
  version: 3.1.11
  epoch: 1
  description: C++ and python library of 2D and 3D vector, matrix, and math operations for computer graphics
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - boost-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - doxygen
      - llvm-18-dev
      - numpy
      - python3-dev
      - samurai

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/AcademySoftwareFoundation/Imath
      expected-commit: 5ac1d5335cb34f0f356c5f2461a57c845b96b115
      tag: v${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -DPYTHON=ON

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: imath-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - imath
    description: imath dev

  - name: py3-imath
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib/
          mv "${{targets.destdir}}"/usr/lib/python3* "${{targets.subpkgdir}}"/usr/lib/
          mv "${{targets.destdir}}"/usr/lib/libPy* "${{targets.subpkgdir}}"/usr/lib/

update:
  enabled: true
  ignore-regex-patterns:
    - "-rc"
    - "Release.*"
  github:
    identifier: AcademySoftwareFoundation/Imath
    use-tag: true
    strip-prefix: v
