package:
  name: iproute2
  version: 6.10.0
  epoch: 0
  description: IP Routing Utilities
  copyright:
    - license: GPL-2.0-or-later

environment:
  contents:
    packages:
      - bash
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - elfutils-dev
      - flex
      - iptables-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://git.kernel.org/pub/scm/network/iproute2/iproute2.git
      tag: v${{package.version}}
      expected-commit: db0edb90d23e99bd5400ad7717f0bf6326430817

  - uses: autoconf/configure
    with:
      opts: |
        --build=${{host.triplet.gnu}} \
        --host=${{host.triplet.gnu}} \
        --prefix=/usr \
        --sysconfdir=/etc \
        --mandir=/usr/share/man \
        --localstatedir=/var

  - uses: autoconf/make
    with:
      opts: |
        CCOPTS="-D_GNU_SOURCE $CFLAGS" LIBDIR=/lib

  - uses: autoconf/make-install

subpackages:
  - name: iproute2-doc
    description: iproute2 documentation
    pipeline:
      - uses: split/manpages

update:
  enabled: true
  release-monitor:
    identifier: 1392
