package:
  name: jaeger-agent
  version: 1.59.0
  epoch: 0
  description: CNCF Jaeger, a Distributed Tracing Platform
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jaegertracing/jaeger
      tag: v${{package.version}}
      expected-commit: 8c9f6c6df758d647f1cdb8b123b34a5743eaf87d

  - runs: |
      make build-agent
      mkdir -p ${{targets.destdir}}/usr/bin
      mv cmd/agent/agent-linux-* ${{targets.destdir}}/usr/bin/jaeger-agent

  - uses: strip

update:
  enabled: true
  github:
    identifier: jaegertracing/jaeger
    strip-prefix: v
