package:
  name: jenkins-plugin-manager
  version: 2.13.0
  epoch: 0
  description: Plugin Manager CLI tool for Jenkins
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - maven
      - openjdk-17
      - openjdk-17-default-jvm
      - wolfi-base
      - wolfi-baselayout
  environment:
    LANG: en_US.UTF-8
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jenkinsci/plugin-installation-manager-tool
      tag: ${{package.version}}
      expected-commit: f9bd96d7be42052fb29c25a3cafbdd7a90d72962

  - runs: |
      mvn clean package -DskipTests

      mkdir -p ${{targets.destdir}}/usr/share/java/jenkins-plugin-manager
      cp plugin-management-cli/target/jenkins-plugin-manager*.jar ${{targets.destdir}}/usr/share/java/${{package.name}}/jenkins-plugin-manager.jar

subpackages:
  - name: ${{package.name}}-compat
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/opt
          ln -s /usr/share/java/${{package.name}}/jenkins-plugin-manager.jar ${{targets.subpkgdir}}/opt/jenkins-plugin-manager.jar

update:
  enabled: true
  github:
    identifier: jenkinsci/plugin-installation-manager-tool
