# Fetches the Jenkins entrypoint script used in the upstream docker image. We
# need this for our image, but as it's stored in a different repo vs the source
# code, we need to fetch it and be able to auto-update.
package:
  name: jenkins-entrypoint
  version: "2.470"
  epoch: 0
  description: Fetches the jenkins entrypoint script from upstream docker repository.
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jenkinsci/docker.git
      tag: ${{package.version}}
      expected-commit: c4de9e46f90035a092834a12804347d56c28300d

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/bin/
      chmod +x jenkins.sh
      cp jenkins.sh ${{targets.destdir}}/usr/local/bin/

update:
  enabled: true
  github:
    identifier: jenkinsci/docker
