package:
  name: jitterentropy-library
  version: 3.5.0
  epoch: 0
  description: Jitterentropy Library
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/smuellerDD/jitterentropy-library
      expected-commit: 48b2ffc128af776ff3658a70e5d7bb4a82180189
      tag: v${{package.version}}

  - runs: |
      # jitterentropy must *not* be compiled with optimizations
      export CFLAGS="$CFLAGS -O0"
      export CPPFLAGS=""
      export CXXFLAGS="$CXXFLAGS -O0"
      # install into /usr
      sed 's|/usr/local|/usr|' -i Makefile
      make
      make install install-static DESTDIR="${{targets.contextdir}}"

  - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    pipeline:
      - uses: split/dev
      - uses: split/manpages
      - uses: split/static
    description: ${{package.name}} development headers and static library

update:
  enabled: true
  github:
    identifier: smuellerDD/jitterentropy-library
    strip-prefix: v
    use-tag: true
