package:
  name: just
  version: 1.33.0
  epoch: 0
  description: "just is a handy way to save and run project-specific commands."
  copyright:
    - license: CC0-1.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - rust
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/casey/just
      expected-commit: 317a85d14c743908d0e8c62f89e79809eaf98e83
      tag: ${{package.version}}

  - name: Configure and build
    runs: |
      cargo auditable build --release
      mkdir -p ${{targets.destdir}}/usr/bin/
      mv target/release/just ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: casey/just
