package:
  name: k8s-sidecar-1.24.6
  version: 1.24.6
  epoch: 0
  description: "python 2 and 3 compatibility library"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-pip
      - py3-setuptools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kiwigrid/k8s-sidecar
      tag: ${{package.version}}
      expected-commit: 8428a776de787d89c2d63e99b7ca57b1f41f7516

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/share/app
      mv src/* ${{targets.destdir}}/usr/share/app
      cd ${{targets.destdir}}/usr/share/app
      python -m venv .venv
      .venv/bin/pip install --no-cache-dir -r requirements.txt
      rm requirements.txt
      find .venv \( -type d -a -name test -o -name tests \) -o \( -type f -a -name '*.pyc' -o -name '*.pyo' \) -exec rm -rf '{}' \+

  - uses: strip

update:
  enabled: true
  github:
    identifier: kiwigrid/k8s-sidecar
    use-tag: true
