package:
  name: k8sgpt-operator
  version: 0.1.6
  epoch: 2
  description: Automatic SRE Superpowers within your Kubernetes cluster
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/k8sgpt-ai/k8sgpt-operator
      tag: v${{package.version}}
      expected-commit: acd6b730aac10dca01d28c6ab5b8b7b68476a7ef

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1

  - uses: go/build
    with:
      packages: .
      output: manager
      ldflags: -w

  - uses: strip

update:
  enabled: true
  github:
    identifier: k8sgpt-ai/k8sgpt-operator
    strip-prefix: v
    use-tag: true
    tag-filter: v
