package:
  name: kor
  version: 0.5.2
  epoch: 1
  description: A Golang Tool to discover unused Kubernetes Resources
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/yonahd/kor
      tag: v${{package.version}}
      expected-commit: 181141dcce1fb608e6982500e88b8f0609b47356

  - uses: go/build
    with:
      modroot: .
      packages: .
      output: kor

  - uses: strip

update:
  enabled: true
  github:
    identifier: yonahd/kor
    strip-prefix: v
