package:
  name: kubernetes-csi-livenessprobe
  version: 2.13.1
  epoch: 0
  description: A sidecar container that can be included in a CSI plugin pod to enable integration with Kubernetes Liveness Probe.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-csi/livenessprobe
      tag: v${{package.version}}
      expected-commit: 426141a24fcd6853380beef1177a88d04d03ccf1

  - uses: go/build
    with:
      packages: ./cmd/livenessprobe
      ldflags: "-s -w -X main.version=v${{package.version}} -extldflags '-static'"
      output: livenessprobe

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-csi/livenessprobe
    strip-prefix: v
