package:
  name: kubernetes-csi-external-provisioner
  version: 5.0.1
  epoch: 3
  description: A dynamic provisioner for Kubernetes CSI plugins.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-csi/external-provisioner
      expected-commit: 33755c1a15f61c2c9e5a8a3bafea55e61678cbb7
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1

  - uses: go/build
    with:
      packages: ./cmd/csi-provisioner
      output: csi-provisioner
      ldflags: -s -w -X main.version=${{package.version}}
      vendor: "true"

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-csi/external-provisioner
    strip-prefix: v
