package:
  name: kubewatch
  version: 2.7.0
  epoch: 1
  description: Watch k8s events and trigger Handlers
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 957dc4a61943136220e2c32a15881928eec81fb4
      repository: https://github.com/robusta-dev/kubewatch
      tag: v${{package.version}}

  # Temporary Fix: Upstream go.sum file does not accurately capture package dependencies.
  - runs: |
      go mod tidy

  - uses: go/build
    with:
      output: kubewatch
      packages: .

  - uses: strip

update:
  enabled: true
  manual: false
  github:
    identifier: robusta-dev/kubewatch
    strip-prefix: v
