package:
  name: kubevela
  version: 1.9.7
  epoch: 4
  description: KubeVela is a modern application delivery platform that makes deploying and operating applications across today's hybrid, multi-cloud environments easier, faster and more reliable
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: fetch
    with:
      expected-sha256: fafb35add4866ac2e09488418bc04039235e6b94625000ab2647ef58ce78733f
      uri: https://github.com/kubevela/kubevela/archive/refs/tags/v${{package.version}}.tar.gz

  - runs: |
      export CGO_ENABLED=0
      export GO111MODULE=on

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.17.0 go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.46.0 go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.46.0 go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc@v1.21.0

  - uses: go/build
    with:
      ldflags: -s -w -X github.com/oam-dev/kubevela/version.VelaVersion=${{package.version}}
      output: manager
      packages: ./cmd/core/main.go

  - uses: go/build
    with:
      ldflags: -s -w -X github.com/oam-dev/kubevela/version.VelaVersion=${{package.version}}
      output: vela
      packages: ./references/cmd/cli/main.go

  - uses: strip

update:
  enabled: true
  manual: false
  github:
    identifier: kubevela/kubevela
    strip-prefix: v
