package:
  name: kuma-2.8
  version: 2.8.2
  epoch: 0
  description: A multi-zone service mesh for containers, Kubernetes and VMs.
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - kuma=${{package.full-version}}
    runtime:
      - ca-certificates-bundle

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+)\.\d+$
    replace: "$1"
    to: major-minor-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kumahq/kuma
      tag: ${{package.version}}
      expected-commit: ffb0a135b8320cd474c503b785b43627d77a1338

subpackages:
  - name: kuma-cp-${{vars.major-minor-version}}
    dependencies:
      provides:
        - kuma-cp=${{vars.major-minor-version}}
    pipeline:
      - uses: go/bump
        with:
          deps: google.golang.org/grpc@v1.64.1
          go-version: "1.22.0"
      - uses: go/build
        with:
          packages: ./app/kuma-cp
          output: kuma-cp
      - uses: strip
    test:
      pipeline:
        - name: Verify kuma-cp
          runs: |
            kuma-cp --help

update:
  enabled: true
  github:
    identifier: kumahq/kuma
    tag-filter: 2.8
    use-tag: true
