package:
  name: kyverno-policy-reporter-ui
  version: 1.9.2
  epoch: 0
  description: Policy Reporter UI
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - curl
      - git
      - go
      - nodejs-16
      - openssl
      - python-3.11
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 15f6a192f947390b30c08a2f900c469cdfe8c160
      repository: https://github.com/kyverno/policy-reporter-ui
      tag: v${{package.version}}

  - runs: |
      export NODE_OPTIONS=--openssl-legacy-provider
      npm install
      npm run generate

      mkdir -p ${{targets.destdir}}/app
      cp -R ./dist ${{targets.destdir}}/app/dist

  - uses: go/build
    with:
      ldflags: -w
      modroot: server
      output: policyreporter-ui
      packages: .

  - uses: strip

subpackages:
  - name: kyverno-policy-reporter-ui-compat
    description: compatibility symlinks package for policyreporter-ui Dockerfile
    pipeline:
      - runs: |
          # Symlink the binary from usr/bin to /app/
          mkdir -p ${{targets.subpkgdir}}/app
          ln -sf /usr/bin/policyreporter-ui ${{targets.subpkgdir}}/app/policyreporter-ui

update:
  enabled: true
  github:
    identifier: kyverno/policy-reporter-ui
    use-tag: true
    strip-prefix: v
