package:
  name: lerna
  version: 8.1.9
  epoch: 10
  description: "Lerna is a fast, modern build system for managing and publishing multiple JavaScript/TypeScript packages from the same repository."
  copyright:
    - license: MIT
  checks:
    disabled:
      - usrlocal
  dependencies:
    runtime:
      - nodejs

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - nodejs
      - npm
      - jq

pipeline:
  - uses: git-checkout
    with:
     repository: https://github.com/lerna/lerna
     expected-commit: 7d1338d884a3e334953ba1ca74924ffa09a60530
     tag: v${{package.version}}
     destination: ${{targets.destdir}}/usr/local/

  - name: npm install
    runs: |
      resolutions='{
            "express": "^4.19.2",
      }'
      jq --argjson resolutions "$resolutions" '.resolutions += $resolutions' ${{targets.destdir}}/usr/local/package.json > temp.json && mv temp.json ${{targets.destdir}}/usr/local/package.json
            
      npm install -prefix ${{targets.destdir}}/usr/local/

update:
  enabled: true
  github:
    identifier: lerna/lerna
    use-tag: true
    tag-filter: v
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - npm
        - git
  pipeline:
    - name: Check Lerna version
      runs: |
        # Verify that Lerna is installed and the version command works
        lerna --version
        lerna --help
    - name: Initialize a Lerna repository
      runs: |
        # Initialize a new Lerna repository and check for success message
        lerna init --independent
