package:
  name: libgcrypt
  version: 1.11.0
  epoch: 0
  description: General purpose crypto library based on the code used in GnuPG
  copyright:
    - license: LGPL-2.1-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libgpg-error-dev
      - texinfo

pipeline:
  - uses: fetch
    with:
      expected-sha256: 09120c9867ce7f2081d6aaa1775386b98c2f2f246135761aae47d81f58685b9c
      uri: https://www.gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-${{package.version}}.tar.bz2

  - uses: autoconf/configure
    with:
      opts: |
        CFLAGS="$CFLAGS -O0" \
        CPPFLAGS="$CPPFLAGS -O0" \
        CXXFLAGS="$CXXLAGS -O0"

  - uses: autoconf/make

  - uses: autoconf/make-install

  - runs: |
      rm -f "${{targets.destdir}}"/usr/share/info/dir

  - uses: strip

subpackages:
  - name: libgcrypt-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libgcrypt
        - libgpg-error-dev
    description: libgcrypt dev

  - name: libgcrypt-doc
    pipeline:
      - uses: split/manpages
    description: libgcrypt manpages

update:
  enabled: true
  release-monitor:
    identifier: 1623
