package:
  name: libmaxminddb
  version: 1.10.0
  epoch: 0
  description: Maxmind GeoIP2 database library
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - curl

pipeline:
  - uses: fetch
    with:
      expected-sha256: 5e6db72df423ae225bfe8897069f6def40faa8931f456b99d79b8b4d664c6671
      uri: https://github.com/maxmind/libmaxminddb/releases/download/${{package.version}}/libmaxminddb-${{package.version}}.tar.gz

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libmaxminddb-static
    pipeline:
      - uses: split/static
    description: libmaxminddb static

  - name: libmaxminddb-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libmaxminddb
        - curl
    description: libmaxminddb dev

  - name: libmaxminddb-doc
    pipeline:
      - uses: split/manpages
    description: libmaxminddb manpages

  - name: libmaxminddb-libs
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib
          mv ${{targets.destdir}}/usr/lib/libmaxminddb.so.* ${{targets.subpkgdir}}/usr/lib/
    description: libmaxminddb libs

update:
  enabled: true
  github:
    identifier: maxmind/libmaxminddb
