package:
  name: libnetfilter_conntrack
  version: "1.0.9"
  epoch: 4
  description: programming interface (API) to the in-kernel connection tracking state table
  copyright:
    - license: GPL-2.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - libmnl-dev
      - libnfnetlink-dev
      - libtool
      - pkgconf-dev

pipeline:
  - uses: git-checkout
    with:
      repository: git://git.netfilter.org/libnetfilter_conntrack
      tag: libnetfilter_conntrack-${{package.version}}
      expected-commit: 9ae15ba15c159a4d6fe46f220fb58b740fc07890

  - runs: |
      ./autogen.sh

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

subpackages:
  - name: libnetfilter_conntrack-dev
    description: libnetfilter_conntrack development files
    pipeline:
      - uses: split/dev

update:
  enabled: true
  release-monitor:
    identifier: 1675
