package:
  name: libnl3
  version: 3.10.0
  epoch: 0
  description: Library for applications dealing with netlink sockets
  copyright:
    - license: LGPL-2.1-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - flex
      - libtool
      - linux-headers
      - pkgconf-dev

var-transforms:
  - from: ${{package.version}}
    match: \.
    replace: _
    to: mangled-package-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/thom311/libnl.git
      tag: libnl${{vars.mangled-package-version}}
      expected-commit: fa05d58ebef426a545b4170b35214492b401c8af

  - runs: |
      ./autogen.sh

  - uses: autoconf/configure
    with:
      opts: |
        --build=$CBUILD \
        --host=$CHOST \
        --prefix=/usr \
        --sysconfdir=/etc \
        --mandir=/usr/share/man \
        --localstatedir=/var \
        --disable-static \
        --enable-unit-tests

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "libnl3-dev"
    description: "headers for libnl3"
    pipeline:
      - uses: split/dev

  - name: "libnl3-cli"
    description: "Command line interface utils for libnl3"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib/
          mv "${{targets.destdir}}"/usr/lib/libnl-cli*.so.* \
            "${{targets.destdir}}"/usr/lib/libnl \
            "${{targets.subpkgdir}}"/usr/lib/
          mv "${{targets.destdir}}"/usr/bin "${{targets.subpkgdir}}"/usr/

update:
  enabled: true
  version-transform:
    - match: "_"
      replace: "."
  github:
    identifier: thom311/libnl
    strip-prefix: libnl
