package:
  name: libnftnl
  version: 1.2.7
  epoch: 0
  description: Netfilter library providing interface to the nf_tables subsystem
  copyright:
    - license: GPL-2.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - jansson-dev
      - libmnl-dev
      - libtool
      - pkgconf-dev

pipeline:
  - uses: git-checkout
    with:
      repository: git://git.netfilter.org/libnftnl
      tag: libnftnl-${{package.version}}
      expected-commit: 116e95aa7b6358c917de8c69f6f173874030b46b

  - runs: |
      ./autogen.sh

  - runs: |
      ./configure \
        --build=$CBUILD \
        --host=$CHOST \
        --prefix=/usr \
        --sysconfdir=/etc \
        --mandir=/usr/share/man \
        --localstatedir=/var \
        --enable-static

  - uses: autoconf/make

  - uses: autoconf/make-install

subpackages:
  - name: libnftnl-dev
    description: libnftnl development files
    pipeline:
      - uses: split/dev

update:
  enabled: true
  release-monitor:
    identifier: 1681
