package:
  name: libpcap
  version: 1.10.4
  epoch: 3
  description: A system-independent interface for user-level packet capture
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - flex
      - linux-headers

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/the-tcpdump-group/libpcap.git
      tag: libpcap-${{package.version}}
      expected-commit: 104271ba4a14de6743e43bcf87536786d8fddea4

  - uses: patch
    with:
      patches: fix-headers.patch

  - uses: autoconf/configure
    with:
      opts: |
        --build=$CBUILD \
        --host=$CHOST \
        --prefix=/usr \
        --sysconfdir=/etc \
        --mandir=/usr/share/man \
        --localstatedir=/var \
        --enable-ipv6

  - runs: |
      ./config.status
      make all shared
      make -j1 DESTDIR="${{targets.destdir}}" install install-shared

  - uses: strip

subpackages:
  - name: "libpcap-dev"
    description: "headers for libpcap"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libpcap

update:
  enabled: true
  github:
    identifier: the-tcpdump-group/libpcap
    strip-prefix: libpcap-
