package:
  name: libtraceevent
  version: 1.8.3
  epoch: 0
  description: "Linux kernel trace event library"
  copyright:
    - license: "LGPL-2.1-or-later AND GPL-2.0-or-later"

environment:
  contents:
    packages:
      - build-base
      - ca-certificates-bundle
      - linux-headers
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://git.kernel.org/pub/scm/libs/libtrace/libtraceevent.git/snapshot/libtraceevent-${{package.version}}.tar.gz
      expected-sha256: 233d88adf5bae6b4511980f0f6314f348326b55fdb3dc9c4212c810e1ab06789

  - uses: autoconf/make

  - runs: |
      make install DESTDIR=${{targets.destdir}} \
        prefix=/usr \
        libdir_relative=lib \
        pkgconfig_dir=/usr/lib/pkgconfig

subpackages:
  - name: libtraceevent-dev
    pipeline:
      - uses: split/dev
    description: libtraceevent dev

  - name: libtraceevent-plugins
    description: plugins for libtraceevent
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib/traceevent/
          mv ${{targets.destdir}}/usr/lib/traceevent/plugins ${{targets.subpkgdir}}/usr/lib/traceevent/

update:
  enabled: true
  release-monitor:
    identifier: 288159
