package:
  name: libxtst
  version: 1.2.4
  epoch: 8
  description: X11 Testing -- Resource extension library
  copyright:
    - license: XFree86-1.1

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libtool
      - libx11-dev
      - libxext-dev
      - libxi-dev
      - pkgconf-dev
      - util-macros
      - xorgproto

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.freedesktop.org/xorg/lib/libxtst.git
      tag: libXtst-${{package.version}}
      expected-commit: 99b89c3bcb0ebb0b6dd86bfdc9d276715eaea889

  - runs: ./autogen.sh

  - uses: autoconf/configure
    with:
      opts: --disable-static

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libxtst-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libxtst
        - libxi-dev
    description: libxtst dev

  - name: libxtst-doc
    pipeline:
      - uses: split/manpages
    description: libxtst manpages

update:
  enabled: true
  release-monitor:
    identifier: 1794
