package:
  name: libxi
  version: 1.8.1
  epoch: 4
  description: X11 Input extension library
  copyright:
    - license: MIT AND X11

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - libtool
      - libx11-dev
      - libxext-dev
      - libxfixes-dev
      - pkgconf-dev
      - util-macros
      - xmlto
      - xorgproto

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.freedesktop.org/xorg/lib/libxi.git
      tag: libXi-${{package.version}}
      expected-commit: 3a7503ec7703f10de17c622ea22b7bff736cea74

  - runs: ./autogen.sh

  - uses: autoconf/configure
    with:
      opts: |
        --with-xmlto \
        --without-fop \
        --disable-static

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libxi-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libxi
        - libxfixes-dev
    description: libxi dev

  - name: libxi-doc
    pipeline:
      - uses: split/manpages
    description: libxi manpages

update:
  enabled: true
  release-monitor:
    identifier: 1778
