package:
  name: loki-3
  version: 3.1.0
  epoch: 1
  description: Like Prometheus, but for logs.
  copyright:
    - license: AGPL-3.0-or-later
  dependencies:
    provides:
      - loki=${{package.full-version}}

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 935aee77ed389c825d36b8d6a85c0d83895a24d1
      repository: https://github.com/grafana/loki
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.6.0 github.com/docker/docker@v26.1.4
      replaces: go.etcd.io/bbolt=go.etcd.io/bbolt@v1.3.6
      show-diff: true

  - uses: autoconf/make

  - runs: |
      mkdir -p ${{targets.contextdir}}/usr/bin
      mv cmd/loki/loki ${{targets.contextdir}}/usr/bin/loki

      # Add the default config
      mkdir -p ${{targets.contextdir}}/etc/loki
      mv cmd/loki/loki-local-config.yaml ${{targets.contextdir}}/etc/loki/local-config.yaml

  - uses: strip

subpackages:
  - name: ${{package.name}}-logcli
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/usr/bin
          mv cmd/logcli/logcli ${{targets.contextdir}}/usr/bin/logcli
    dependencies:
      provides:
        - logcli=${{package.full-version}}
    test:
      pipeline:
        - runs: |
            logcli --version

  - name: ${{package.name}}-promtail
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/usr/bin
          mv clients/cmd/promtail/promtail ${{targets.contextdir}}/usr/bin/promtail

          mkdir -p ${{targets.contextdir}}/etc/promtail
          mv clients/cmd/promtail/promtail-local-config.yaml ${{targets.contextdir}}/etc/promtail/config.yml
    dependencies:
      provides:
        - promtail=${{package.full-version}}
    test:
      pipeline:
        - runs: |
            promtail --version

  - name: ${{package.name}}-loki-canary
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/usr/bin
          mv cmd/loki-canary/loki-canary ${{targets.contextdir}}/usr/bin/loki-canary
    dependencies:
      provides:
        - loki-canary=${{package.full-version}}
    test:
      pipeline:
        - runs: |
            loki-canary --version

update:
  enabled: true
  github:
    identifier: grafana/loki
    strip-prefix: v
    tag-filter: v3

test:
  pipeline:
    - runs: |
        loki --version
