package:
  name: nano
  version: "8.1"
  epoch: 0
  description: "The Nano package contains a small, simple text editor which aims to replace Pico, the default editor in the Pine package."
  copyright:
    - license: LGPL-2.1-or-later

environment:
  contents:
    packages:
      - build-base
      - ncurses-dev
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://www.nano-editor.org/dist/v8/nano-${{package.version}}.tar.gz
      expected-sha256: 6508bfbcfe38153ecbdc1b7d3479323564353f134acc8c501910220371390675

  - uses: autoconf/configure
    with:
      opts: |
        --disable-debug \
        --disable-dependency-tracking \
        --prefix=/usr \
        --sysconfdir=/etc \
        --enable-color \
        --enable-extra \
        --enable-multibuffer \
        --enable-nanorc \
        --enable-utf8

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

test:
  pipeline:
    - name: Verify Nano installation
      runs: |
        nano --version || exit 1

update:
  enabled: true
  release-monitor:
    identifier: 2046
