package:
  name: nghttp2
  version: 1.62.1
  epoch: 1
  description: "experimental HTTP/2 client, server and library"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - autoconf
      - build-base
      - busybox
      - c-ares-dev
      - ca-certificates-bundle
      - libev-dev
      - libtool
      - openssl-dev
      - pkgconf-dev
      - wolfi-base
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/nghttp2/nghttp2.git
      tag: v${{package.version}}
      expected-commit: d13a5758373931064636c1641db6277db45552dc

  - runs: autoreconf -vfi

  - uses: autoconf/configure
    with:
      opts: --enable-app

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "nghttp2-dev"
    description: "headers for nghttp2"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - nghttp2

  - name: "nghttp2-doc"
    description: "documentation for nghttp2"
    pipeline:
      - uses: split/manpages

  - name: "libnghttp2-14"
    description: "nghttp2 client library"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libnghttp2.so.* "${{targets.subpkgdir}}"/usr/lib/

update:
  enabled: true
  github:
    identifier: nghttp2/nghttp2
    strip-prefix: v
