package:
  name: node-feature-discovery-0.16
  version: 0.16.3
  epoch: 1
  description: Node feature discovery for Kubernetes
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - node-feature-discovery=${{package.full-version}}

environment:
  contents:
    packages:
      - protoc

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/node-feature-discovery
      tag: v${{package.version}}
      expected-commit: 6030c974d38ed9a1e4592f0f133d64e27d3c50a7

  - name: copy conf
    runs: |
      mkdir -p ${{targets.contextdir}}/etc/kubernetes/node-feature-discovery/
      cp ./deployment/components/worker-config/nfd-worker.conf.example ${{targets.contextdir}}/etc/kubernetes/node-feature-discovery/nfd-worker.conf

  - uses: go/bump
    with:
      deps: k8s.io/kubernetes@v1.30.3
      replaces: k8s.io/apiserver=k8s.io/apiserver@v0.30.3 k8s.io/apimachinery=k8s.io/apimachinery@v0.30.3 k8s.io/client-go=k8s.io/client-go@v0.30.3
      modroot: .

  - uses: go/build
    with:
      modroot: .
      packages: ./cmd/kubectl-nfd
      output: kubectl-nfd
      tags: osusergo,netgo
      ldflags: "-X sigs.k8s.io/node-feature-discovery/pkg/version.version=${{package.version}} -X sigs.k8s.io/node-feature-discovery/pkg/utils/hostpath.pathPrefix=/host-"
      go-package: go

  - uses: go/build
    with:
      modroot: .
      packages: ./cmd/nfd-gc
      output: nfd-gc
      tags: osusergo,netgo
      ldflags: "-X sigs.k8s.io/node-feature-discovery/pkg/version.version=${{package.version}} -X sigs.k8s.io/node-feature-discovery/pkg/utils/hostpath.pathPrefix=/host-"
      go-package: go

  - uses: go/build
    with:
      modroot: .
      packages: ./cmd/nfd-master
      output: nfd-master
      tags: osusergo,netgo
      ldflags: "-X sigs.k8s.io/node-feature-discovery/pkg/version.version=${{package.version}} -X sigs.k8s.io/node-feature-discovery/pkg/utils/hostpath.pathPrefix=/host-"
      go-package: go

  - uses: go/build
    with:
      modroot: .
      packages: ./cmd/nfd-topology-updater
      output: nfd-topology-updater
      tags: osusergo,netgo
      ldflags: "-X sigs.k8s.io/node-feature-discovery/pkg/version.version=${{package.version}} -X sigs.k8s.io/node-feature-discovery/pkg/utils/hostpath.pathPrefix=/host-"
      go-package: go

  - uses: go/build
    with:
      modroot: .
      packages: ./cmd/nfd-worker
      output: nfd-worker
      tags: osusergo,netgo
      ldflags: "-X sigs.k8s.io/node-feature-discovery/pkg/version.version=${{package.version}} -X sigs.k8s.io/node-feature-discovery/pkg/utils/hostpath.pathPrefix=/host-"
      go-package: go

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/node-feature-discovery
    strip-prefix: v
    use-tag: true
    tag-filter: v0.16.

test:
  pipeline:
    - runs: kubectl-nfd -h
    - runs: nfd-gc -version
    - runs: nfd-master -version
    - runs: nfd-topology-updater -version
    - runs: nfd-worker -version
