package:
  name: nri-discovery-kubernetes
  version: 1.9.2
  epoch: 0
  description: New Relic Kubernetes Auto-Discovery
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nri-discovery-kubernetes
      expected-commit: 76351caadb96b3bb5da5bee2a59b83842c45cc52
      tag: v${{package.version}}

  - uses: go/build
    with:
      modroot: .
      packages: ./cmd/discovery/
      output: nri-discovery-kubernetes
      ldflags: -s -w

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    description: "Compatibility package to place binaries in the location expected by newrelic-infrastructure-bundle"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/var/db/newrelic-infra
          ln -sf /usr/bin/${{package.name}} ${{targets.subpkgdir}}/var/db/newrelic-infra/${{package.name}}

update:
  enabled: true
  github:
    identifier: newrelic/nri-discovery-kubernetes
    strip-prefix: v
