package:
  name: nsc
  version: 2.8.6
  epoch: 8
  description: Tool for creating nkey/jwt based configurations
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/nats-io/nsc
      tag: v${{package.version}}
      expected-commit: bcb05a434540c0e6b936746a2dfa878e6d28b1cb

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.23.0
      modroot: .

  - uses: go/build
    with:
      packages: .
      modroot: .
      output: nsc
      ldflags: -X main.version=${{package.version}} -X main.commit=$(git rev-parse HEAD) -X main.date=$(date ${SOURCE_DATE_EPOCH:+ -d@${SOURCE_DATE_EPOCH}} "+%Y-%m-%dT%H:%M:%SZ")

update:
  enabled: true
  github:
    identifier: nats-io/nsc
    strip-prefix: v
