package:
  name: octo-sts
  version: 0.3.0
  epoch: 0
  description: A GitHub App that acts like a Security Token Service (STS) for the Github API.
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      destination: octo-sts
      expected-commit: 9853c4800d4a3b632964a8c05dea366b5490dd1c
      repository: https://github.com/octo-sts/app
      tag: v${{package.version}}

  - uses: go/build
    with:
      modroot: octo-sts
      output: octo-sts
      packages: ./cmd/app

  - uses: strip

update:
  enabled: true
  github:
    identifier: octo-sts/app
    strip-prefix: v
