package:
  name: opam
  version: 2.2.0
  epoch: 0
  description: "opam is a source-based package manager. It supports multiple simultaneous compiler installations, flexible package constraints, and a Git-friendly development workflow."
  copyright:
    - license: LGPL-2.1-only WITH OCaml-LGPL-linking-exception

environment:
  contents:
    packages:
      - acl-dev
      - binutils-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - curl-dev
      - gawk
      - libacl1
      - libcurl-openssl4
      - ocaml
      - ocaml-compiler-libs
      - ocaml-dev
      - patch
      - wget
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ocaml/opam
      tag: ${{package.version}}
      expected-commit: 8e00bd7f8fcb68d2435ef1ffc6cde338470cc532

  - runs: |
      ./configure \
      --build=$CBUILD \
      --host=$CHOST \
      --prefix=/usr \
      --sysconfdir=/etc \
      --mandir=/usr/share/man \
      --infodir=/usr/share/info \
      --localstatedir=/var \
      --with-mccs \
      --with-vendored-deps

      make -j1 lib-ext all

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: opam-doc
    pipeline:
      - uses: split/manpages

update:
  enabled: true
  github:
    identifier: ocaml/opam
