package:
  name: openssf-compiler-options
  version: 20240627
  epoch: 0
  description: "Compiler Options Hardening Guide for C and C++"
  url: https://best.openssf.org/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.html
  copyright:
    - license: CC-BY-4.0

environment:
  contents:
    packages:
      - busybox

pipeline:
  - name: Install
    runs: |
      mkdir -p "${{targets.destdir}}"
      cp -r etc usr "${{targets.destdir}}"
      for i in $(seq 15 18); do
        ln -s clang "${{targets.destdir}}"/etc/clang-$i
      done

test:
  environment:
    contents:
      packages:
        - clang-18
        - gcc
        - gcc-12
  pipeline:
    - uses: test/compiler-hardening-check
      with:
        cc: clang-18
    - uses: test/compiler-hardening-check
      with:
        cc: gcc
    - uses: test/compiler-hardening-check
      with:
        cc: gcc-12

update:
  enabled: false
