package:
  name: orc
  version: 0.4.39
  epoch: 0
  description: Oil Run-time Compiler
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - linux-headers
      - meson

pipeline:
  - uses: fetch
    with:
      expected-sha512: 5b2167c9bb5ef4fdd5b1a683e5e7fc94bafa0afe62cb5f30e6fd2de9e80b4727b533029688e2807fc64b60af45f9263a421074bf330fb2f208b48620b0f95fd6
      uri: https://gstreamer.freedesktop.org/src/orc/orc-${{package.version}}.tar.xz

  - uses: meson/configure
    with:
      opts: |
        -Db_lto=true \
        -Dorc-test=disabled

  - uses: meson/compile

  - uses: meson/install

  - uses: strip

subpackages:
  - name: ${{package.name}}-compiler
    description: ${{package.name}} compiler
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv ${{targets.destdir}}/usr/bin/orcc ${{targets.subpkgdir}}/usr/bin

  - name: ${{package.name}}-dev
    pipeline:
      - uses: split/dev
    description: ${{package.name}} dev

update:
  enabled: true
  release-monitor:
    identifier: 2573
