package:
  name: parallel
  version: "20240722"
  epoch: 0
  description: "GNU parallel is a shell tool for executing jobs in parallel using one or more computers"
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - perl

pipeline:
  - uses: fetch
    with:
      uri: https://ftp.gnu.org/gnu/parallel/parallel-${{package.version}}.tar.bz2
      expected-sha256: c7335471f776af28bea9464ad85a50f2ed120f78fbf75ead6647aeea8e0e53f0

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 5448
