package:
  name: percona-server-8.3
  version: 8.3.0
  epoch: 2
  description: "Percona Server for MySQL is a free, fully compatible, enhanced, and open source drop-in replacement for any MySQL database. It provides superior performance, scalability, and instrumentation."
  copyright:
    - license: GPL-3.0-or-later
    - license: BSD-3-Clause
  dependencies:
    provides:
      - percona-server=${{package.full-version}}

environment:
  contents:
    packages:
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - curl-dev
      - libaio-dev
      - libedit
      - libevent-dev
      - libtirpc-dev
      - linux-pam-dev
      - ncurses-dev
      - nfs-utils
      - openldap-dev
      - openssl-dev
      - pcre2-dev
      - perl
      - readline-dev
      - rpcgen
      - samurai
      - sed
      - wolfi-baselayout
      - xz-dev
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/percona/percona-server
      tag: Percona-Server-${{package.version}}-1
      expected-commit: fcee26ff5d51b9e72fa8b3b626a3424e2cbe2794

  - name: "Update Submodules"
    runs: |
      git submodule update --init --recursive

  - name: "Remove Coredumper Support"
    runs: |
      sed -i 's/INCLUDE(coredumper)//g' CMakeLists.txt
      sed -i 's/MYSQL_CHECK_COREDUMPER()//g' CMakeLists.txt
      sed -i 's/OPTION (WITH_COREDUMPER "Enable support for coredumper library" ON)//g' CMakeLists.txt

  - name: "Licencing"
    runs: |
      mkdir /usr/share/percona-server
      mkdir /usr/share/percona-server/licenses
      mkdir /usr/share/percona-server/licenses/curl
      mkdir /usr/share/percona-server/licenses/zstd
      mkdir /usr/share/percona-server/licenses/innobase
      mkdir /usr/share/percona-server/licenses/libtirpc
      mkdir /usr/share/percona-server/licenses/innodb
      mkdir /usr/share/percona-server/licenses/libedit
      mkdir /usr/share/percona-server/licenses/cmake

      cp LICENSE ../../usr/share/percona-server/licenses/
      cp extra/curl/curl-8.4.0/COPYING ../../usr/share/percona-server/licenses/curl/
      cp extra/zstd/zstd-1.5.5/COPYING ../../usr/share/percona-server/licenses/zstd/
      cp storage/innobase/COPYING.Google ../../usr/share/percona-server/licenses/innobase/
      cp storage/innobase/COPYING.Percona ../../usr/share/percona-server/licenses/innobase/
      cp extra/tirpc/libtirpc-1.3.3/COPYING ../../usr/share/percona-server/licenses/libtirpc/
      cp COPYING.innodb-deadlock-count-patch ../../usr/share/percona-server/licenses/innodb/
      cp extra/libedit/libedit-20221030-3.1/COPYING ../../usr/share/percona-server/licenses/libedit/
      cp extra/libevent/libevent-2.1.11-stable/cmake/COPYING-CMAKE-SCRIPTS ../../usr/share/percona-server/licenses/cmake/

  - name: "Cmake"
    runs: |
      mkdir /var/tmp
      cmake . -G Ninja \
        -DFORCE_INSOURCE_BUILD=1 \
        -DBUILD_CONFIG=mysql_release \
        -DWITH_EDITLINE=system \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DSYSCONFDIR=/etc \
        -DMYSQL_DATADIR=/var/lib/mysql \
        -DMYSQL_UNIX_ADDR=/run/mysqld/mysqld.sock \
        -DDEFAULT_CHARSET=utf8mb4 \
        -DDEFAULT_COLLATION=utf8mb4_general_ci \
        -DENABLED_LOCAL_INFILE=ON \
        -DINSTALL_INFODIR=share/info \
        -DINSTALL_MANDIR=share/man \
        -DINSTALL_PLUGINDIR=lib/${{package.name}}/plugin \
        -DINSTALL_INCLUDEDIR=include/mysql \
        -DINSTALL_DOCREADMEDIR=share/doc/${{package.name}} \
        -DINSTALL_SUPPORTFILESDIR=share/${{package.name}} \
        -DINSTALL_DOCDIR=share/doc/${{package.name}} \
        -DWITH_ROCKSDB=NO \
        -DTMPDIR=/var/tmp \
        -DWITH_ASAN=OFF \
        -DWITH_EXTRA_CHARSETS=complex \
        -DWITH_SYSTEMD=no \
        -DWITH_SSL=system \
        -DWITH_VALGRIND=OFF \
        -DWITH_ZLIB=system \

  - name: "Install"
    runs: |
      DESTDIR="${{targets.destdir}}" ninja install

  - name: "Remove extras"
    runs: |
      rm -rf "${{targets.destdir}}"/usr/mysql-test
      rm -rf "${{targets.destdir}}"/usr/lib/libmysqlclient.so
      rm -rf "${{targets.destdir}}"/usr/lib/libmysqlclient_r.so

  - name: "Create required data directories"
    runs: |
      mkdir -p "${{targets.destdir}}"/run/mysqld
      mkdir -p "${{targets.destdir}}"/var/lib/mysql
      mkdir -p "${{targets.destdir}}"/var/tmp

subpackages:
  - name: "${{package.name}}-dev"
    description: "headers for percona-server"
    pipeline:
      - uses: split/dev

  - name: ${{package.name}}-oci-entrypoint
    description: Entrypoint for percona-server in OCI containers
    dependencies:
      runtime:
        - bash
        - busybox
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin/
          cp docker-entrypoint.sh ${{targets.subpkgdir}}/usr/bin/
          chmod +x ${{targets.subpkgdir}}/usr/bin/docker-entrypoint.sh

  - name: ${{package.name}}-oci-entrypoint-compat
    pipeline:
      - runs: |
          # Symlink the binary from usr/bin to /
          mkdir -p "${{targets.subpkgdir}}"
          mkdir -p "${{targets.subpkgdir}}"/usr/local/bin
          ln -sf /usr/bin/docker-entrypoint.sh ${{targets.subpkgdir}}/entrypoint.sh
          ln -sf /usr/bin/docker-entrypoint.sh ${{targets.subpkgdir}}/usr/local/bin/docker-entrypoint.sh
    dependencies:
      runtime:
        - ${{package.name}}-oci-entrypoint

update:
  manual: true

test:
  pipeline:
    - runs: |
        mysqld --initialize
