package:
  name: perl-clone
  version: "0.46"
  epoch: 3
  description: Clone perl module
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - perl
      - perl-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/garu/Clone.git
      tag: ${{package.version}}
      expected-commit: 7f73e27bc6371e26e3d0a58d9abac31ea61edd54

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

subpackages:
  - name: perl-clone-doc
    pipeline:
      - uses: split/manpages
    description: perl-clone manpages

update:
  enabled: true
  github:
    identifier: garu/Clone
    use-tag: true
