package:
  name: perl-http-message
  version: "6.46"
  epoch: 2
  description: HTTP style message
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl-clone
      - perl-encode-locale
      - perl-http-date
      - perl-io-html
      - perl-lwp-mediatypes
      - perl-uri

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - perl
      - perl-clone
      - perl-encode-locale
      - perl-http-date
      - perl-io-html
      - perl-lwp-mediatypes
      - perl-uri

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/libwww-perl/HTTP-Message.git
      tag: v${{package.version}}
      expected-commit: bc0a61c3eabcec470414c4c0aaa0f3c955ca9a30

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: perl-http-message-doc
    pipeline:
      - uses: split/manpages
    description: perl-http-message manpages

update:
  enabled: true
  github:
    identifier: libwww-perl/HTTP-Message
    use-tag: true
    strip-prefix: v
