package:
  name: pgcat
  version: 1.1.1
  epoch: 2
  description: "PostgreSQL pooler with sharding, load balancing and failover support."
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - rust
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/postgresml/pgcat
      tag: v${{package.version}}
      expected-commit: 1f2c6507f7fb5461df1a599c0b380aa114597bb5

  - name: Configure and build
    runs: |
      cargo auditable build --release -vv
      mkdir -p ${{targets.destdir}}/usr/bin/
      mv target/release/pgcat ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - 'pgcat'
    - 'alpha'
    - 'beta'
    - 'sharded'
    - 'simple'
  github:
    identifier: postgresml/pgcat
    strip-prefix: v
    use-tag: true
