package:
  name: php-8.2-redis
  version: 6.0.2
  epoch: 1
  description: "A PHP extension for Redis"
  copyright:
    - license: PHP-3.01
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-8.2
      - php-8.2-igbinary

environment:
  contents:
    packages:
      - autoconf
      - build-base
      - busybox
      - php-8.2
      - php-8.2-dev
      - php-8.2-igbinary-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/phpredis/phpredis
      tag: ${{package.version}}
      expected-commit: 62cf943fecc5182c6329b332df43cf28012cef55

  - name: Prepare build
    runs: phpize

  - name: Configure
    runs: ./configure --enable-redis-igbinary

  - uses: autoconf/make

  - name: Make install
    runs: |
      INSTALL_ROOT="${{targets.destdir}}" DESTDIR="${{targets.destdir}}" make install

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=redis.so" > "${{targets.subpkgdir}}/etc/php/conf.d/redis.ini"

  - name: ${{package.name}}-dev
    description: PHP 8.2 redis development headers
    pipeline:
      - uses: split/dev

update:
  enabled: true
  github:
    identifier: phpredis/phpredis
