package:
  name: php-8.2-pecl-pdosqlsrv
  version: 5.11.1
  epoch: 2
  description: "Provides PHP 8.2 Microsoft Drivers for SQL Server (PDO_SQLSRV) - PECL"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - php-8.2

environment:
  contents:
    packages:
      - autoconf
      - automake
      - binutils
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - gcc
      - libtool
      - php-8.2-dev
      - unixodbc-dev

pipeline:
  - uses: fetch
    with:
      uri: https://pecl.php.net/get/pdo_sqlsrv-${{package.version}}.tgz
      expected-sha512: 6bcf39b9948fdc06261f4e901de988c33b27422d5677c6ec8234625f49ad702186e5e02bcb5264945e0bc5fd4de3389ec014e125856625837dbd884776747faa

  - uses: pecl/phpize

  - uses: autoconf/make

  # TODO: This is a temporary workaround until the pecl/install pipelines
  # propagates through.
  # https://github.com/chainguard-dev/melange/pull/1068
  - name: Install
    runs: |
      make INSTALL_ROOT="${{targets.destdir}}" install
      install -d ${{targets.destdir}}/etc/php/conf.d
      echo "extension=pdo_sqlsrv.so" > ${{targets.destdir}}/etc/php/conf.d/pdo_sqlsrv.ini

  - uses: strip

update:
  enabled: false
  exclude-reason: >
    TODO(vaikas): I can find the releases in github but building it does not work with fetching from there like it does when you use fetch. Also seems like I can't watch the github repo for new releases, yet use the fetch above together?

