package:
  name: php-8.1-pecl-sqlsrv
  version: 5.11.1
  epoch: 2
  description: "Provides PHP 8.1 Microsoft Drivers for SQL Server (SQLSRV) - PECL"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - php-8.1

environment:
  contents:
    packages:
      - autoconf
      - automake
      - binutils
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - gcc
      - libtool
      - php-8.1-dev
      - unixodbc-dev

pipeline:
  - uses: fetch
    with:
      uri: https://pecl.php.net/get/sqlsrv-${{package.version}}.tgz
      expected-sha512: ee63d7225b7ea8d26e8f53ed25e94fb356cefd3c463405bad1a3543edb820c6b5e3c554842b0190352c521c7aa314f42b6590b8b3cb859fead1f05348fb43f46

  - uses: pecl/phpize

  - uses: autoconf/make

  # TODO: This is a temporary workaround until the pecl/install pipelines
  # propagates through.
  # https://github.com/chainguard-dev/melange/pull/1068
  - name: Install
    runs: |
      make INSTALL_ROOT="${{targets.destdir}}" install
      install -d ${{targets.destdir}}/etc/php/conf.d
      echo "extension=sqlsrv.so" > ${{targets.destdir}}/etc/php/conf.d/sqlsrv.ini

  - uses: strip

update:
  enabled: false
  exclude-reason: >
    TODO(vaikas): I can find the releases in github but building it does not work with fetching from there like it does when you use fetch. Also seems like I can't watch the github repo for new releases, yet use the fetch above together?

