package:
  name: php-8.2-msgpack
  version: 2.2.0
  epoch: 2
  description: "A PHP extension for msgpack"
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-8.2

environment:
  contents:
    packages:
      - autoconf
      - build-base
      - busybox
      - php-8.2
      - php-8.2-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/msgpack/msgpack-php
      # The tag has a msgpack- prefix, but the version does not.
      tag: msgpack-${{package.version}}
      expected-commit: 472e987b916b51df3d8e8fabd0608e243419c5d8

  - name: Prepare build
    runs: phpize

  - name: Configure
    runs: ./configure --with-msgpack

  - uses: autoconf/make

  - name: Make install
    runs: |
      INSTALL_ROOT="${{targets.destdir}}" DESTDIR="${{targets.destdir}}" make install

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=msgpack.so" > "${{targets.subpkgdir}}/etc/php/conf.d/msgpack.ini"

  - name: ${{package.name}}-dev
    description: PHP 8.2 msgpack development headers
    pipeline:
      - uses: split/dev

update:
  enabled: true
  github:
    identifier: msgpack/msgpack-php
    tag-filter-prefix: msgpack-
    strip-prefix: msgpack-
