package:
  name: php-8.1-pecl-http
  version: 4.2.3
  epoch: 5
  description: "Provides PHP 8.1 HTTP module for PHP Extended HTTP Support- PECL"
  copyright:
    - license: BSD-2-Clause
  dependencies:
    runtime:
      - php-8.1

environment:
  contents:
    packages:
      - autoconf
      - automake
      - binutils
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - curl-dev
      - gcc
      - icu-dev
      - libtool
      - openssl-dev
      - php-8.1-dev
      - php-8.1-pecl-raphf
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: https://pecl.php.net/get/pecl_http-${{package.version}}.tgz
      expected-sha512: be8bac0947e9fb63da5afa3eaf7b75a70775ca59a8a8c24b5f4b1875909dd8b6b2f4b25bf462acef78f18d5dd739c02352786853d9963cb71f3c1b114f113558

  - uses: pecl/phpize

  - uses: autoconf/make

  # TODO: This is a temporary workaround until the pecl/install pipelines
  # propagates through.
  # https://github.com/chainguard-dev/melange/pull/1068
  - name: Install
    runs: |
      make INSTALL_ROOT="${{targets.destdir}}" install
      install -d ${{targets.destdir}}/etc/php/conf.d
      echo "extension=http.so" > ${{targets.destdir}}/etc/php/conf.d/http.ini

  - uses: strip

update:
  enabled: false
