package:
  name: postgres-operator
  version: 1.12.2
  epoch: 1
  description: Postgres operator creates and manages PostgreSQL clusters running in Kubernetes
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 7c7aa969350bef67d0283d93589499ae3d114edb
      repository: https://github.com/zalando/postgres-operator.git
      tag: v${{package.version}}

  - uses: go/build
    with:
      modroot: .
      packages: ./cmd
      output: postgres-operator
      ldflags: -X=main.version=${{package.version}}

  - uses: strip

subpackages:
  - name: postgres-operator-compat
    description: "Compatibility package to place binaries in the location expected by upstream helm charts"
    pipeline:
      - runs: |
          # The helm chart/dockerfile expects the postgres-operator binaries to be in / instead of /usr/bin
          mkdir -p "${{targets.subpkgdir}}"
          ln -sf /usr/bin/postgres-operator ${{targets.subpkgdir}}/postgres-operator

update:
  enabled: true
  github:
    identifier: zalando/postgres-operator
    strip-prefix: v

test:
  pipeline:
    - runs: |
        /usr/bin/postgres-operator --help
