package:
  name: py3-more-itertools
  version: 10.3.0
  epoch: 0
  description: "more routines for operating on iterables, beyond itertools"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-pip
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/more-itertools/more-itertools.git
      tag: v${{package.version}}
      expected-commit: 7e46c39ea5d73b80f36ef2faf266e10108029b02

  - runs: pip install . --prefix=/usr --root=${{targets.destdir}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: more-itertools/more-itertools
    strip-prefix: v
