package:
  name: py3-keras-applications
  version: 1.0.8
  epoch: 1
  description: Reference implementations of popular deep learning models
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - numpy
      - py3-h5py
      - python-3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python-3
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      expected-sha256: 5579f9a12bcde9748f4a12233925a59b93b73ae6947409ff34aa2ba258189fe5
      uri: https://files.pythonhosted.org/packages/source/K/Keras-Applications/Keras_Applications-${{package.version}}.tar.gz

  - name: Python Build
    uses: python/build

  - name: Python Install
    uses: python/install

  - uses: strip

update:
  enabled: false
  exclude-reason: >
    The modular keras-preprocessing package has been retired upstream in favor of monolithic "keras" package, but Tensorflow itself has not made the jump yet.

