package:
  name: py3-charset-normalizer
  version: 3.3.2
  epoch: 4
  description: "offers you an alternative to Universal Charset Encoding Detector, also known as Chardet"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jawah/charset_normalizer.git
      tag: ${{package.version}}
      expected-commit: 79dce4857914fead2ffe55eb787cad6d5cf14643

  - runs: |
      sed -i '/cov-report/d' setup.cfg
      python3 setup.py build

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}" --skip-build

  - uses: strip

update:
  enabled: true
  github:
    identifier: jawah/charset_normalizer

test:
  pipeline:
    - uses: python/import
      with:
        import: charset_normalizer
