package:
  name: py3-testtools
  version: 2.7.2
  epoch: 0
  description: Extensions to the Python standard library unit testing framework
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - py3-setuptools
      - python-3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - python-3
      - wolfi-base
  environment:
    # This is needed to work around the error "ValueError: ZIP does not support timestamps before 1980"
    SOURCE_DATE_EPOCH: 315532800

pipeline:
  - uses: git-checkout
    with:
      expected-commit: ac6919f5ead31ed331710dff921211e9c7440840
      repository: https://github.com/testing-cabal/testtools
      tag: ${{package.version}}

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

update:
  enabled: true
  manual: false
  github:
    identifier: testing-cabal/testtools
