package:
  name: py3-pyyaml
  version: 6.0.1
  epoch: 5
  description: "Python3 bindings for YAML"
  copyright:
    - license: MIT
  dependencies:
    provider-priority: 0

vars:
  pypi-package: pyyaml

data:
  - name: py-versions
    items:
      3.10: "310"
      3.11: "311"
      3.12: "312"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - py3-cython
      - py3-supported-pip
      - py3-supported-python-dev
      - py3-supported-wheel
      - yaml-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/yaml/pyyaml
      tag: ${{package.version}}
      expected-commit: c42fa3bff1eabdb64763bb1526d9ea1ccb708479

  # from: https://github.com/yaml/pyyaml/issues/601#issuecomment-1740811121
  - uses: patch
    with:
      patches: pyyaml-cython3.patch

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
    pipeline:
      - runs: python${{range.key}} setup.py clean --all
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip

  - name: py3-wheels-${{vars.pypi-package}}
    pipeline:
      - uses: py/collect-wheels

update:
  enabled: true
  ignore-regex-patterns:
    - dec-*
  github:
    identifier: yaml/pyyaml
    use-tag: true
