package:
  name: py3-zaproxy
  version: 0.3.2
  epoch: 1
  description: ZAP Python API
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - py3-requests
      - py3-six

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/zaproxy/zap-api-python/
      expected-commit: a779d751b3d7c20cb629c760c4cef0da0796dc6f
      tag: ${{package.version}}

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import zapv2

update:
  enabled: true
  ignore-regex-patterns:
    - '.*\.dev1$'
  github:
    identifier: zaproxy/zap-api-python
    use-tag: true
