package:
  name: py3-matplotlib
  version: 3.9.1
  epoch: 0
  description: Python plotting package
  copyright:
    - license: PSF-2.0
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - numpy
      - py3-cairo
      - py3-certifi
      - py3-contourpy
      - py3-cycler
      - py3-dateutil
      - py3-fonttools
      - py3-kiwisolver
      - py3-packaging
      - py3-parsing
      - py3-pillow
      - py3-pybind11-dev
      - py3-setuptools-scm
      - py3-tkinter
      - py3-tz
      - python3
      - python3-dev
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/matplotlib/matplotlib
      expected-commit: 44be14cc3a866e28a9ad22f36abfe8c0623cc6ac
      tag: v${{package.version}}

  - name: Python Build
    runs: meson setup . output --prefix=/usr

  - uses: meson/compile

  - uses: meson/install

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - 'rc'
  github:
    identifier: matplotlib/matplotlib
    strip-prefix: v
    use-tag: true
