package:
  name: py3-kubernetes-asyncio
  version: 30.3.0
  epoch: 0
  description: Kubernetes asynchronous python client
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - py3-aiohttp
      - py3-certifi
      - py3-dateutil
      - py3-pyyaml
      - py3-setuptools
      - py3-six
      - py3-urllib3
      - python-3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python-3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tomplus/kubernetes_asyncio
      expected-commit: 6d3287040b4f21a2ae44866f6c41c28fb71b91fa
      tag: ${{package.version}}

  - name: Python Build
    uses: python/build

  - name: Python Install
    uses: python/install

  - uses: strip

update:
  enabled: true
  github:
    identifier: tomplus/kubernetes_asyncio
    use-tag: true
