package:
  name: py3-build
  version: 1.2.1
  epoch: 4
  description: A simple, correct Python build frontend
  copyright:
    - license: MIT
  dependencies:
    provider-priority: 0

vars:
  pypi-package: build

data:
  - name: py-versions
    items:
      3.10: "310"
      3.11: "311"
      3.12: "312"

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - py3-supported-flit-core
      - py3-supported-pip
      - py3-supported-python
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pypa/build
      tag: ${{package.version}}
      expected-commit: 1e67c062e9d1b1a6d5ffed621f4b29902bb764e5

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-packaging
        - py${{range.key}}-pyproject-hooks
        - py${{range.key}}-tomli
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}

  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}-bin
    description: Executable binaries for ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      runtime:
        - py${{range.key}}-${{vars.pypi-package}}
      provides:
        - py3-${{vars.pypi-package}}
      provider-priority: ${{range.value}}
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/usr
          mv ${{targets.contextdir}}/../py${{range.key}}-${{vars.pypi-package}}/usr/bin ${{targets.contextdir}}/usr

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}

test:
  pipeline:
    - runs: python3.12 -c "import ${{vars.pypi-package}}"

update:
  enabled: true
  ignore-regex-patterns:
    - post
  github:
    identifier: pypa/build
    use-tag: true
    strip-suffix: .post1
