package:
  name: py3-pillow
  version: 10.4.0
  epoch: 0
  description: Python Imaging Library (Fork)
  copyright:
    - license: HPND
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - freetype-dev
      - fribidi-dev
      - lcms2-dev
      - libjpeg-turbo-dev
      - libpng-dev
      - libwebp-dev
      - libxcb-dev
      - openjpeg-dev
      - py3-gpep517
      - py3-setuptools
      - py3-wheel
      - python3
      - python3-dev
      - tiff-dev
      - wolfi-base
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/python-pillow/Pillow
      expected-commit: 9b4fae77178e827ab17118fbc89c739ffd6a0fab
      tag: ${{package.version}}

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: python-pillow/Pillow
