package:
  name: py3-magic
  version: 0.4.27
  epoch: 7
  description: "Python3 wrapper for libmagic"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - libmagic

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ahupp/python-magic
      tag: ${{package.version}}
      expected-commit: b443195104d89363b93a547584c1a12fce3b57ec

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import magic

update:
  enabled: true
  github:
    identifier: ahupp/python-magic
    use-tag: true
