package:
  name: py3-maturin
  version: 1.7.0
  epoch: 1
  description: Build and publish crates with pyo3, rust-cpython and cffi bindings as well as rust binaries as python packages
  copyright:
    - license: MIT OR Apache-2.0
  dependencies:
    runtime:
      - py3-tomli

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - python3-dev
      - rust
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 2061d01bf40ee4c753cc03b84e22ac226a962414
      repository: https://github.com/pyo3/maturin
      tag: v${{package.version}}

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import maturin

update:
  enabled: true
  ignore-regex-patterns:
    - 'beta'
  github:
    identifier: pyo3/maturin
    strip-prefix: v
