package:
  name: py3-protobuf
  version: 5.27.3
  epoch: 0
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - protobuf-dev
      - py3-setuptools
      - py3-wheel
      - python3
      - python3-dev
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/p/protobuf/protobuf-${{package.version}}.tar.gz
      expected-sha256: 82460903e640f2b7e34ee81a947fdaad89de796d324bcbc38ff5430bcdead82c

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 46522
