package:
  name: py3-toml
  version: 0.10.2
  epoch: 1
  description: "Python Library for Tom's Obvious, Minimal Language"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 3f637dba5f68db63d4b30967fedda51c82459471
      repository: https://github.com/uiri/toml
      tag: ${{package.version}}

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import toml

update:
  enabled: true
  github:
    identifier: uiri/toml
    use-tag: true
