package:
  name: py3-tenacity
  version: 9.0.0
  epoch: 0
  description: "General-purpose retrying library, written in Python, to simplify the task of adding retry behavior to just about anything"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - python3-dev
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jd/tenacity.git
      tag: ${{package.version}}
      expected-commit: a662bbb487cd6d34541824589f8e8c7a1f7791bb

  - uses: python/build-wheel

  - uses: strip

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import tenacity

update:
  enabled: true
  github:
    identifier: jd/tenacity
    use-tag: true
  ignore-regex-patterns:
    - 'mergify2-'
