package:
  name: py3-networkx
  version: "3.3"
  epoch: 1
  description: Python package for creating and manipulating graphs and networks
  copyright:
    - license: BSD-3-Clause
  dependencies:
    provider-priority: 0

vars:
  pypi-package: networkx

data:
  - name: py-versions
    items:
      3.10: "310"
      3.11: "311"
      3.12: "312"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - py3-supported-build
      - py3-supported-pip
      - py3-supported-python
      - py3-supported-wheel

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/networkx/networkx
      expected-commit: 7fdddfa2caa8275f7862c46524b803db99ff2cde
      tag: networkx-${{package.version}}

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      provides:
        - py3-${{vars.pypi-package}}
      provider-priority: ${{range.value}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.pypi-package}}

update:
  enabled: true
  github:
    identifier: networkx/networkx
    strip-prefix: networkx-
