package:
  name: py3-jwcrypto
  version: 1.5.6
  epoch: 1
  description: Implementation of JOSE Web standards
  copyright:
    - license: LGPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/latchset/jwcrypto
      tag: v${{package.version}}
      expected-commit: ecde4efdc7c9364b53bd1b4232e97557d821abdf

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import jwcrypto

update:
  enabled: true
  github:
    identifier: latchset/jwcrypto
    strip-prefix: v
