package:
  name: py3-jinja2
  version: 3.1.4
  epoch: 1
  description: "A small but fast and easy to use stand-alone python template engine"
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - py3-markupsafe

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-flit-core
      - py3-gpep517
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - python3-dev
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/j/jinja2/jinja2-${{package.version}}.tar.gz
      expected-sha512: d07d68a2687af68c705d3b7f5a2c67aca7b9d125316b15085888b9d0d6e769981af76f6f524728b89b5501bd671d518fcb2638f9ae112e57ca2bf2a53482cd89

  - runs: |
      python3 -m gpep517 build-wheel --wheel-dir .dist --output-fd 3 3>&1 >&2
      python3 -m installer -d "${{targets.destdir}}" .dist/*.whl

      docdir="/usr/share/doc/${{package.name}}"
      # Note: The documentation in the docs directory needs to be generated
      # by py-sphinx, however, this package (py-jinja2) is a dependency of
      # Sphinx itself!
      mkdir -p "$docdir"
      cp -R docs "$docdir"/

      install -m 644 -D LICENSE.txt /usr/share/licenses/${{package.name}}/LICENSE.txt

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 3894

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import jinja2
