package:
  name: py3.11-crcmod
  version: "1.7"
  epoch: 0
  description: Cyclic Redundancy Check (CRC) implementation in Python
  copyright:
    - license: 'MIT'
  dependencies:
    runtime:
      - python-3.11

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3.11-setuptools
      - python-3.11
      - python-3.11-dev
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/c/crcmod/crcmod-${{package.version}}.tar.gz
      expected-sha256: dc7051a0db5f2bd48665a990d3ec1cc305a466a77358ca4492826f41f283601e

  - runs: |
      python setup.py build

  - runs: |
      python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 12017

test:
  pipeline:
    - runs: |
        LIBRARY="crcmod"
        IMPORT_STATEMENT="import crcmod"

        if ! python -c "$IMPORT_STATEMENT"; then
            echo "Failed to import library '$LIBRARY'."
            python -c "$IMPORT_STATEMENT" 2>&1
            exit 1
        else
            echo "Library '$LIBRARY' is installed and can be imported successfully."
            exit 0
        fi
