# NOTE: This is not a complete rancher-2.8 package with all the components.
# This is just created for the purpose of building the rancher-agent package.
vars:
  CATTLE_SYSTEM_CHART_DEFAULT_BRANCH: release-v2.8
  CATTLE_CHART_DEFAULT_BRANCH: release-v2.8
  CATTLE_PARTNER_CHART_DEFAULT_BRANCH: main
  CATTLE_RKE2_CHART_DEFAULT_BRANCH: main
  CATTLE_KDM_BRANCH: release-v2.8
  LOGLEVEL_VERSION: 0.1.5

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+\.\d+)\.\d+$
    replace: "$1"
    to: major-minor-version

package:
  name: rancher-2.8
  version: 2.8.5
  epoch: 0
  description: Complete container management platform
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - rancher=${{package.full-version}}

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates
      - go
      - perl-utils
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rancher/rancher
      tag: v${{package.version}}
      expected-commit: 7af1354e9b8900cec6e5360787e291acd376e6d3

subpackages:
  - name: rancher-agent-${{vars.major-minor-version}}
    dependencies:
      provides:
        - rancher-agent=${{package.full-version}}
      runtime:
        - kubectl
        - tini
        - rancher-kontainer-driver-metadata-${{vars.major-minor-version}}
        - rancher-system-charts-${{vars.major-minor-version}}
        - rancher-partner-charts-${{vars.major-minor-version}}
        - rancher-charts-${{vars.major-minor-version}}
        - rancher-loglevel-${{vars.major-minor-version}}
        - rancher-rke2-charts-${{vars.major-minor-version}}
        - rancher-helm3-charts-${{vars.major-minor-version}}
    pipeline:
      - uses: go/bump
        with:
          deps: github.com/crewjam/saml@v0.4.14 github.com/go-jose/go-jose/v3@v3.0.3 github.com/hashicorp/go-retryablehttp@v0.7.7 google.golang.org/protobuf@v1.33.0 golang.org/x/net@v0.23.0 k8s.io/kubernetes@v1.28.12 k8s.io/apiserver@v0.28.12 github.com/rancher/apiserver@v0.0.0-20240207153957-4fd7d821d952 github.com/rancher/norman@v0.0.0-20240207153100-3bb70b772b52
          modroot: .
      - uses: go/build
        with:
          packages: ./cmd/agent
          output: agent
          ldflags: |
            -X main.VERSION=${{package.version}}
          tags: k8s
    test:
      pipeline:
        - runs: |
            agent | grep "Rancher agent version ${{package.version}}"

  - name: rancher-kontainer-driver-metadata-${{vars.major-minor-version}}
    dependencies:
      provides:
        - rancher-kontainer-driver-metadata=${{package.full-version}}
    pipeline:
      - uses: git-checkout
        with:
          repository: https://github.com/rancher/kontainer-driver-metadata/
          branch: ${{vars.CATTLE_KDM_BRANCH}}
          expected-commit: c331ba8be30b10d6bf6fbd341d43da6c03214803
          destination: kontainer-driver-metadata
      - working-directory: ./kontainer-driver-metadata
        runs: |
          mkdir -p ${{targets.contextdir}}/var/lib/rancher-data/driver-metadata
          install -Dm755 data/data.json  ${{targets.contextdir}}/var/lib/rancher-data/driver-metadata/data.json
    test:
      pipeline:
        - runs: |
            # check the expected files are available at the expected location at `/var/lib/rancher-data/driver-metadata/`
            test -f /var/lib/rancher-data/driver-metadata/data.json

  - name: rancher-system-charts-${{vars.major-minor-version}}
    dependencies:
      provides:
        - rancher-system-charts=${{package.full-version}}
    pipeline:
      - uses: git-checkout
        with:
          repository: https://github.com/rancher/system-charts
          branch: ${{vars.CATTLE_SYSTEM_CHART_DEFAULT_BRANCH}}
          destination: system-charts
          expected-commit: 1eb0ac24e9e4d50bd0666f6530d05f45c9158994
      - working-directory: ./system-charts
        runs: |
          mkdir -p ${{targets.contextdir}}/var/lib/rancher-data/local-catalogs/system-library
          cp -r ./*  ${{targets.contextdir}}/var/lib/rancher-data/local-catalogs/system-library
    test:
      pipeline:
        - runs: |
            # check the expected files are available at the expected location at `/var/lib/rancher-data/local-catalogs/system-library/`
            test -f /var/lib/rancher-data/local-catalogs/system-library/README.md

  - name: rancher-partner-charts-${{vars.major-minor-version}}
    dependencies:
      provides:
        - rancher-partner-charts=${{package.full-version}}
    pipeline:
      - uses: git-checkout
        with:
          repository: https://github.com/rancher/partner-charts
          branch: ${{vars.CATTLE_PARTNER_CHART_DEFAULT_BRANCH}}
          destination: partner-charts
          expected-commit: 00460454010ae9083847290b4426000e10618b52
      - working-directory: ./partner-charts
        runs: |
          shasum256=$(echo -n "https://git.rancher.io/partner-charts" |shasum -a 256 | awk '{ print $1 }')
          mkdir -p ${{targets.contextdir}}/var/lib/rancher-data/local-catalogs/v2/rancher-partner-charts/$shasum256
          cp -r ./* ${{targets.contextdir}}/var/lib/rancher-data/local-catalogs/v2/rancher-partner-charts/$shasum256
    test:
      environment:
        contents:
          packages:
            - perl-utils
      pipeline:
        - runs: |
            shasum256=$(echo -n "https://git.rancher.io/partner-charts" |shasum -a 256 | awk '{ print $1 }')
            # check the expected files are available at the expected location at `/var/lib/rancher-data/local-catalogs/v2/rancher-partner-charts/$shasum256/`
            test -f /var/lib/rancher-data/local-catalogs/v2/rancher-partner-charts/$shasum256/README.md

  - name: rancher-charts-${{vars.major-minor-version}}
    dependencies:
      provides:
        - rancher-charts=${{package.full-version}}
    pipeline:
      - uses: git-checkout
        with:
          repository: https://github.com/rancher/charts
          branch: ${{vars.CATTLE_CHART_DEFAULT_BRANCH}}
          destination: charts
          expected-commit: 0ccfd2651d7edc49c10a3e4204ecf742c1df6a02
          depth: -1
      - working-directory: ./charts
        runs: |
          shasum256=$(echo -n "https://git.rancher.io/charts" |shasum -a 256 | awk '{ print $1 }')
          mkdir -p ${{targets.contextdir}}/var/lib/rancher-data/local-catalogs/v2/rancher-charts/$shasum256
          cp -r ./* ${{targets.contextdir}}/var/lib/rancher-data/local-catalogs/v2/rancher-charts/$shasum256
      - working-directory: ./charts
        runs: |
          git checkout master
          mkdir -p ${{targets.contextdir}}/var/lib/rancher-data/local-catalogs/library
          cp -r ./* ${{targets.contextdir}}/var/lib/rancher-data/local-catalogs/library
    test:
      environment:
        contents:
          packages:
            - perl-utils
      pipeline:
        - runs: |
            shasum256=$(echo -n "https://git.rancher.io/charts" |shasum -a 256 | awk '{ print $1 }')
            # check the expected files are available at the expected location at `/var/lib/rancher-data/local-catalogs/v2/rancher-charts/$shasum256/`
            test -f /var/lib/rancher-data/local-catalogs/v2/rancher-charts/$shasum256/README.md
            # check the expected files are available at the expected location at `/var/lib/rancher-data/local-catalogs/library/`
            test -f /var/lib/rancher-data/local-catalogs/library/README.md

  - name: rancher-rke2-charts-${{vars.major-minor-version}}
    dependencies:
      provides:
        - rancher-rke2-charts=${{package.full-version}}
    pipeline:
      - uses: git-checkout
        with:
          repository: https://github.com/rancher/rke2-charts
          branch: ${{vars.CATTLE_RKE2_CHART_DEFAULT_BRANCH}}
          destination: rke2-charts
          expected-commit: 1452f6cafad83cc2b5dacb286be64d002dedcdab
      - working-directory: ./rke2-charts
        runs: |
          shasum256=$(echo -n "https://git.rancher.io/rke2-charts" |shasum -a 256 | awk '{ print $1 }')
          mkdir -p ${{targets.contextdir}}/var/lib/rancher-data/local-catalogs/v2/rancher-rke2-charts/$shasum256
          cp -r ./* ${{targets.contextdir}}/var/lib/rancher-data/local-catalogs/v2/rancher-rke2-charts/$shasum256
    test:
      environment:
        contents:
          packages:
            - perl-utils
      pipeline:
        - runs: |
            shasum256=$(echo -n "https://git.rancher.io/rke2-charts" |shasum -a 256 | awk '{ print $1 }')
            # check the expected files are available at the expected location at `/var/lib/rancher-data/local-catalogs/v2/rancher-rke2-charts/$shasum256/`
            test -f /var/lib/rancher-data/local-catalogs/v2/rancher-rke2-charts/$shasum256/README.md

  - name: rancher-helm3-charts-${{vars.major-minor-version}}
    dependencies:
      provides:
        - rancher-helm3-charts=${{package.full-version}}
    pipeline:
      - uses: git-checkout
        with:
          repository: https://github.com/rancher/helm3-charts
          branch: master
          destination: helm3-charts
          expected-commit: c6986e9372b206e9c93f4d53de5a8fa46f210960
      - working-directory: ./helm3-charts
        runs: |
          mkdir -p ${{targets.contextdir}}/var/lib/rancher-data/local-catalogs/helm3-library
          cp -r ./* ${{targets.contextdir}}/var/lib/rancher-data/local-catalogs/helm3-library
    test:
      pipeline:
        - runs: |
            # check the expected files are available at the expected location at `/var/lib/rancher-data/local-catalogs/helm3-library/`
            test -f /var/lib/rancher-data/local-catalogs/helm3-library/README.md

  - name: rancher-loglevel-${{vars.major-minor-version}}
    dependencies:
      provides:
        - rancher-loglevel=${{package.full-version}}
    pipeline:
      - uses: git-checkout
        with:
          expected-commit: 54744f948c5b400647b8b2b7d7bcd5285789eae7
          repository: https://github.com/rancher/loglevel
          tag: v${{vars.LOGLEVEL_VERSION}}
          destination: loglevel
      - uses: go/build
        with:
          ldflags: -X main.Version={{package.version}}
          modroot: loglevel
          output: loglevel
          packages: .
    test:
      pipeline:
        - runs: |
            loglevel -v

update:
  enabled: true
  github:
    identifier: rancher/rancher
    strip-prefix: v
    use-tag: true
    tag-filter: v2.8.
