package:
  name: rclone
  version: 1.67.0
  epoch: 1
  description: rsync for cloud storage - Google Drive, S3, Dropbox, Backblaze B2, One Drive, Swift, Hubic, Wasabi, Google Cloud Storage, Yandex Files
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - fuse3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 93e8a976ef686a4bd8e3afaf2016734c81881507
      repository: https://github.com/rclone/rclone
      tag: v${{package.version}}

  - runs: |
      CGO_ENABLED=0 make
      mkdir -p ${{targets.destdir}}/usr/bin
      mv rclone ${{targets.destdir}}/usr/bin/rclone

  - uses: strip

update:
  enabled: true
  github:
    identifier: rclone/rclone
    strip-prefix: v
    use-tag: true
