package:
  name: readline
  version: "8.2"
  epoch: 7
  description: "GNU readline library"
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - ncurses-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: f7a382fd09319b20ef4435b9b554183b605468c1
      repository: https://git.savannah.gnu.org/git/readline.git
      tag: readline-${{package.version}}

  - uses: patch
    with:
      patches: fix-rl_do_undo-crash.patch
      strip-components: 0

  - uses: patch
    with:
      patches: fix-ncurses-underlinking.patch
      strip-components: 0

  - uses: patch
    with:
      patches: readline82-001.patch readline82-002.patch readline82-003.patch readline82-004.patch readline82-005.patch readline82-006.patch readline82-007.patch readline82-008.patch readline82-009.patch readline82-010.patch
      strip-components: 0

  - name: Configure
    runs: |
      # Needed to ensure ncurses linked
      export LDFLAGS=$(echo $LDFLAGS | sed 's/,--as-needed//g')
      ./configure \
         --host=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "readline-dev"
    description: "GNU readline headers"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - readline

update:
  enabled: true
  release-monitor:
    identifier: 4173
