package:
  name: ripgrep
  version: 14.1.0
  epoch: 1
  description: "ripgrep recursively searches directories for a regex pattern while respecting your gitignore"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - rust
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/BurntSushi/ripgrep
      expected-commit: e50df40a1967708b9781486b1c017e48040bceb0
      tag: ${{package.version}}

  - name: Configure and build
    runs: |
      cargo auditable build --release --features 'pcre2'
      mkdir -p ${{targets.destdir}}/usr/bin/
      mv target/release/rg ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: BurntSushi/ripgrep
