package:
  name: ruby3.2-io-event
  version: 1.6.5
  epoch: 0
  description: An event loop.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

vars:
  gem: io-event

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 3abd3a8fddb57b7d794ba0abe1d3d908355bef4f
      repository: https://github.com/socketry/io-event
      tag: v${{package.version}}

  - uses: patch
    with:
      patches: 001-remove-signing-key.patch

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: socketry/io-event
    strip-prefix: v
