package:
  name: ruby3.2-protocol-http
  version: 0.28.1
  epoch: 0
  description: Provides abstractions to handle HTTP protocols.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

vars:
  gem: protocol-http

pipeline:
  - uses: git-checkout
    with:
      expected-commit: a472da19cd2fc8b23a75d647ca6c76197f712d09
      repository: https://github.com/socketry/protocol-http
      tag: v${{package.version}}

  - uses: patch
    with:
      patches: 001-remove-signing-key.patch

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: socketry/protocol-http
    strip-prefix: v
    use-tag: true
