package:
  name: ruby3.2-net-imap
  version: 0.4.14
  epoch: 2
  description: Ruby client api for Internet Message Access Protocol
  copyright:
    - license: Ruby
    - license: BSD-2-Clause
  dependencies:
    runtime:
      - ruby3.2-date
      - ruby3.2-net-protocol

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: e588adbf05101f98cb6f804fbd5ae6e8bf9be5f6
      repository: https://github.com/ruby/net-imap
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

vars:
  gem: net-imap

update:
  enabled: true
  github:
    identifier: ruby/net-imap
    strip-prefix: v
    use-tag: true
