package:
  name: runc
  version: 1.1.13
  epoch: 1
  description: CLI tool for spawning and running containers according to the OCI specification
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - go-md2man
      - libseccomp-dev
      - libtool

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/opencontainers/runc
      tag: v${{package.version}}
      expected-commit: 58aa9203c123022138b22cf96540c284876a7910

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0

  - runs: |
      make COMMIT=$(git rev-parse HEAD)
      make man
      install -Dsm755 ./runc "${{targets.destdir}}"/usr/bin/runc
      install -Dm644 ./man/man8/* -t "${{targets.destdir}}"/usr/share/man/man8/

  - uses: strip

subpackages:
  - name: runc-doc
    pipeline:
      - uses: split/manpages
    description: runc manpages

update:
  enabled: true
  github:
    identifier: opencontainers/runc
    strip-prefix: v
