package:
  name: rye
  version: 0.37.0
  epoch: 1
  description: "An Experimental Package Management Solution for Python"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - openssl-dev
      - perl
      - rust
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/astral-sh/rye
      expected-commit: 09b67c469d92acb6d31d561176c7f43e2947ea62
      tag: ${{package.version}}

  - name: Configure and build
    runs: |
      cargo auditable build --release
      mkdir -p ${{targets.destdir}}/usr/bin/
      mv target/release/${{package.name}} ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: astral-sh/rye
