package:
  name: sbomqs
  version: 0.1.7
  epoch: 0
  description: SBOM quality score - Quality metrics for your sboms
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/interlynk-io/sbomqs
      tag: v${{package.version}}
      expected-commit: 14e7376fa2b00c102a9ba89fd5ccc7cf26f2f255

  - uses: go/build
    with:
      packages: .
      modroot: .
      output: sbomqs
      ldflags: -X sigs.k8s.io/release-utils/version.gitVersion=${{package.version}} -X sigs.k8s.io/release-utils/version.gitCommit=$(git rev-parse HEAD) -X sigs.k8s.io/release-utils/version.buildDate=$(date ${SOURCE_DATE_EPOCH:+ -d@${SOURCE_DATE_EPOCH}} "+%Y-%m-%dT%H:%M:%SZ")

  - uses: strip

update:
  enabled: true
  github:
    identifier: interlynk-io/sbomqs
    tag-filter: v
    strip-prefix: v
