package:
  name: skaffold
  version: 2.10.0
  epoch: 2
  description: Easy and Repeatable Kubernetes Development
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - make

pipeline:
  - uses: git-checkout
    with:
      expected-commit: cbc665bfc1fe7253df466e70dd48e3851d935a3e
      repository: https://github.com/GoogleContainerTools/skaffold
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/cloudflare/circl@v1.3.7 github.com/containerd/containerd@v1.7.11 github.com/docker/docker@v24.0.7 github.com/sigstore/cosign/v2@v2.2.1

  - runs: |
      make
      install -m755 -D ./out/skaffold "${{targets.destdir}}"/usr/bin/skaffold

  - uses: strip

update:
  enabled: true
  github:
    identifier: GoogleContainerTools/skaffold
    strip-prefix: v
    tag-filter: v
