package:
  name: sops
  version: 3.9.0
  epoch: 2
  description: Simple and flexible tool for managing secrets
  copyright:
    - license: MPL-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/getsops/sops
      tag: v${{package.version}}
      expected-commit: 19259529106022b62f758956c04f025c832a1f11

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: .

  - uses: go/build
    with:
      modroot: .
      packages: ./cmd/sops
      output: sops

  - uses: strip

update:
  enabled: true
  github:
    identifier: getsops/sops
    strip-prefix: v
