package:
  name: sqlpad
  version: 7.4.1 # when updating check the patch below as it contains dependency version updates which may downgrade if upstream upgrades them
  epoch: 1
  description: Web-based SQL editor. Legacy project in maintenance mode.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - nodejs-20 # currently needs node 20, to check in the future see, https://github.com/sqlpad/sqlpad/blob/master/.nvmrc
      - yarn

environment:
  contents:
    packages:
      - build-base
      - busybox
      - jq
      - nodejs
      - python-3.11
      - yarn

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sqlpad/sqlpad
      expected-commit: 5929bbb5ca78e187952673f454a84aabe80e304a
      tag: v${{package.version}}

  - working-directory: /home/build/server
    runs: |
      yarn install

  - uses: patch
    with:
      patches: build-sh.patch

  - runs: |
      ./scripts/build.sh
      mkdir -p ${{targets.destdir}}/usr/bin
      mv server ${{targets.destdir}}/usr/bin/sqlpad-server

      # Remove files adding unnecessary/incorrect shebang deps: dtrace and groovy
      rm ${{targets.destdir}}/usr/bin/sqlpad-server/node_modules/cassandra-driver/Jenkinsfile
      rm ${{targets.destdir}}/usr/bin/sqlpad-server/node_modules/ldapjs/examples/snoopldap.d

  - uses: strip

subpackages:
  - name: "${{package.name}}-compat"
    description: "Compatibility package to place binaries in the location expected by upstream"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/app
          ln -s /usr/bin/sqlpad-server ${{targets.subpkgdir}}/usr/app
    test:
      pipeline:
        - runs: |
            test -L /usr/app/sqlpad-server

test:
  environment:
    contents:
      packages:
        - curl
        - sqlpad-compat
        - shadow
        - coreutils
    environment:
      HOME: /root
  pipeline:
    - name: "Test SQLPad"
      uses: test/daemon-check-output
      with:
        setup: |
          #!/bin/sh
          # Node requires the current user to have a home directory configured.
          useradd -u 1000 -d /root testuser
        start: node /usr/app/sqlpad-server/server.js --dbPath /var/lib/sqlpad --port 3000
        timeout: 30
        expected_output: |
          Migration finished
          Welcome to SQLPad!
        post: |
          curl -s http://localhost:3000 | grep "<title>SQLPad</title>"

update:
  enabled: true
  github:
    identifier: sqlpad/sqlpad
    strip-prefix: v
