package:
  name: step-issuer
  version: 0.9.3
  epoch: 0
  description: A certificate issuer for cert-manager using step certificates CA
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/smallstep/step-issuer
      tag: v${{package.version}}
      expected-commit: 49821b651b9284ec04fe7f24ad6211f6841d2ad6

  - uses: go/build
    with:
      packages: ./
      output: step-issuer
      ldflags: -w -X "main.Version=${{package.version}}"

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    dependencies:
      runtime:
        - step-issuer
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}
          ln -sf /usr/bin/step-issuer ${{targets.contextdir}}/manager
    description: Helm chart compatability
    test:
      pipeline:
        - runs: |
            /manager -h

update:
  enabled: true
  github:
    identifier: smallstep/step-issuer
    strip-prefix: v

test:
  pipeline:
    - name: Run Help Command
      runs: |
        /usr/bin/step-issuer -h
