package:
  name: task
  version: 3.38.0
  epoch: 1
  description: A task runner / simpler Make alternative written in Go
  copyright:
    - license: MIT
      paths:
        - "*"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/go-task/task
      tag: v${{package.version}}
      expected-commit: 88b095020e14defcce4645e72f503eb5d880f78d

  - uses: go/build
    with:
      packages: ./cmd/task
      modroot: .
      output: task

update:
  enabled: true
  github:
    identifier: go-task/task
    strip-prefix: v
