package:
  name: tcpdump
  version: 4.99.4
  epoch: 2
  description: A tool for network monitoring and data acquisition
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - libpcap-dev
      - openssl-dev
      - samurai

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 55bc126b0216cfe409b8d6bd378f65679d136ddf
      repository: https://github.com/the-tcpdump-group/tcpdump.git
      tag: tcpdump-${{package.version}}

  - runs: |
      cmake -B build -G Ninja \
        -DCMAKE_BUILD_TYPE=None \
        -DCMAKE_INSTALL_PREFIX=/usr
      cmake --build build
      DESTDIR="${{targets.destdir}}" cmake --install build

  - uses: strip

subpackages:
  - name: "tcpdump-doc"
    description: "tcpdump manpages"
    pipeline:
      - uses: split/manpages

update:
  enabled: true
  github:
    identifier: the-tcpdump-group/tcpdump
    strip-prefix: tcpdump-
