package:
  name: tdb
  version: 1.4.11
  epoch: 0
  description: The tdb library
  copyright:
    - license: LGPL-3.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - python3
      - python3-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 4e8ba6d93f383565bbd061be4deee15318232d1bbcca7212f18e17f56bb975a8
      uri: https://samba.org/ftp/tdb/tdb-${{package.version}}.tar.gz

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: tdb-dev
    pipeline:
      - uses: split/dev
    description: tdb dev

  - name: py3-tdb
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/python3* "${{targets.contextdir}}"/usr/lib/

update:
  enabled: true
  release-monitor:
    identifier: 1735
