package:
  name: temporal
  version: 0.13.2
  epoch: 1
  description: Command-line interface for running Temporal Server and interacting with Workflows, Activities, Namespaces, and other parts of Temporal
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - wolfi-baselayout
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/temporalio/cli
      tag: v${{package.version}}
      expected-commit: ba831c3ab6b1188d67778176c49f2bd354716769

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1

  - uses: go/build
    with:
      packages: ./cmd/temporal
      output: temporal

  - uses: strip

subpackages:
  - name: temporal-compat
    description: "Compat package for temporal"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/local/bin
          ln -s /usr/bin/temporal "${{targets.contextdir}}"/usr/local/bin

update:
  enabled: true
  github:
    identifier: temporalio/cli
    strip-prefix: v
