package:
  name: terraform-docs
  version: 0.18.0
  epoch: 3
  description: Generate documentation from Terraform modules in various output formats
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/terraform-docs/terraform-docs
      tag: v${{package.version}}
      expected-commit: 228c7a7284650b140e6a1d7ae26b383fc4f8a502

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1

  - uses: go/build
    with:
      packages: .
      output: terraform-docs

test:
  pipeline:
    - runs: ls -lh /usr/bin && terraform-docs --help

update:
  enabled: true
  github:
    identifier: terraform-docs/terraform-docs
    strip-prefix: v
    tag-filter: v
