package:
  name: thanos
  version: 0.36.0
  epoch: 0
  description: Highly available Prometheus setup with long term storage capabilities.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - busybox
      - ca-certificates-bundle
      - curl
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: cfff5518d37756715a1cee43c42b21f4afccfbf2
      repository: https://github.com/thanos-io/thanos
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.6.0

  - runs: |
      make build

  - runs: |
      install -Dm755 "$(go env GOPATH)"/bin/thanos "${{targets.destdir}}"/usr/bin/thanos

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - rc*
  github:
    identifier: thanos-io/thanos
    strip-prefix: v
    tag-filter: v
