package:
  name: thin-provisioning-tools
  version: 1.0.13
  epoch: 1
  description: "suite of tools for manipulating the metadata of the dm-thin device-mapper target"
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - coreutils
      - gawk
      - rust
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jthornber/thin-provisioning-tools
      expected-commit: 116c05345bed5fe727992c3458311606d5443ff6
      tag: v${{package.version}}

  - runs: |
      cargo auditable build --release
      make install DESTDIR="${{targets.destdir}}"

  - uses: strip

subpackages:
  - name: "thin-provisioning-tools-dev"
    description: "headers for thin-provisioning-tools"
    pipeline:
      - uses: split/dev

  - name: "thin-provisioning-tools-doc"
    description: "docs for thin-provisioning-tools"
    pipeline:
      - uses: split/manpages

update:
  enabled: true
  github:
    identifier: jthornber/thin-provisioning-tools
    strip-prefix: v
    use-tag: true
    tag-filter: v
