package:
  name: tigerbeetle
  version: 0.15.4
  epoch: 0
  description: "The distributed financial accounting database designed for mission critical safety and performance."
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - zig

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tigerbeetledb/tigerbeetle
      tag: ${{package.version}}
      expected-commit: 14abaeabd09bd7c78a95b6b990748f3612b3e4cc

  - runs: |
      zig build -Drelease

      mkdir -p ${{targets.destdir}}/usr/bin
      mv zig-out/bin/tigerbeetle ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: tigerbeetledb/tigerbeetle
    strip-prefix: v
    use-tag: true
    # There are some prereleases with a weird WEEKLY format.
    tag-filter: 0.
