package:
  name: wash
  version: 0.29.2
  epoch: 1
  description: "WAsmcloud SHell - a comprehensive command-line tool for wasmCloud development"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/wasmCloud/wasmCloud
      tag: wash-cli-v${{package.version}}
      expected-commit: 38996c0dc59343be1514714d07cb7da922645d93

  - name: Configure and build
    runs: |
      cargo auditable build --release --manifest-path=crates/wash-cli/Cargo.toml
      mkdir -p ${{targets.destdir}}/usr/bin/
      mv target/release/wash ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: wasmcloud/wasmcloud
    strip-prefix: wash-cli-v
    tag-filter-prefix: wash-cli-v

test:
  pipeline:
    - name: Verify wash installation
      runs: |
        wash --version || exit 1
