package:
  name: wasmer
  version: 4.3.5
  epoch: 0
  description: The leading WebAssembly Runtime supporting WASI and Emscripten.
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/wasmerio/wasmer
      tag: v${{package.version}}
      expected-commit: 491cba4badf39a9aca2062fbff387693a25b1bca

  - runs: |
      make build-wasmer build-capi
      mkdir -p ${{targets.destdir}}/usr/bin
      mv target/release/wasmer ${{targets.destdir}}/usr/bin/

  - uses: strip

subpackages:
  - name: wasmer-capi
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib
          mv target/release/libwasmer.so ${{targets.subpkgdir}}/usr/lib/

update:
  enabled: true
  github:
    identifier: wasmerio/wasmer
    strip-prefix: v
