package:
  name: wayland
  version: 1.23.0
  epoch: 0
  description: A computer display server protocol
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - expat-dev
      - libffi-dev
      - libxml2-dev
      - meson

pipeline:
  - uses: fetch
    with:
      expected-sha256: 05b3e1574d3e67626b5974f862f36b5b427c7ceeb965cb36a4e6c2d342e45ab2
      uri: https://gitlab.freedesktop.org/wayland/wayland/-/releases/${{package.version}}/downloads/wayland-${{package.version}}.tar.xz

  - uses: meson/configure
    with:
      opts: |
        -Db_lto=true \
        -Ddocumentation=false

  - uses: meson/compile

  - uses: meson/install

  - uses: strip

data:
  - name: libs
    items:
      client:
      egl:
      cursor:
      server:

subpackages:
  - name: wayland-dev
    pipeline:
      - uses: split/dev
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/share
          mv ${{targets.destdir}}/usr/bin ${{targets.subpkgdir}}/usr/
          mv ${{targets.destdir}}/usr/share/* ${{targets.subpkgdir}}/usr/share/
    dependencies:
      runtime:
        - wayland
        - libffi-dev
        - expat-dev
        - wayland-libs-client
        - wayland-libs-cursor
        - wayland-libs-egl
        - wayland-libs-server
    description: wayland dev

  - range: libs
    name: wayland-libs-${{range.key}}
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib
          mv ${{targets.destdir}}/usr/lib/libwayland-${{range.key}}.so.* ${{targets.subpkgdir}}/usr/lib/
    description: wayland ${{range.key}} libs

update:
  enabled: true
  release-monitor:
    identifier: 10061
