package:
  name: weaviate
  version: 1.23.0
  epoch: 1
  description: Weaviate is an open source vector database that stores both objects and vectors, allowing for combining vector search with structured filtering with the fault-tolerance and scalability of a cloud-native database, all accessible through GraphQL, REST, and various language clients.
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: bbf8c87e9b5d7218098aa329bcc81443ea431cb3
      repository: https://github.com/weaviate/weaviate
      tag: v${{package.version}}

  - runs: |
      mkdir -p ${{targets.destdir}}/bin
      GITHASH=$(git rev-parse --short HEAD)

      # Mitigate GHSA-45x7-px36-x8w8
      go get golang.org/x/crypto@v0.17.0

      go build \
        -ldflags '-w -extldflags "-static" -X github.com/weaviate/weaviate/usecases/config.GitHash='"$GITHASH"'' \
        -o ${{targets.destdir}}/bin/weaviate ./cmd/weaviate-server

  - uses: strip

update:
  enabled: true
  manual: false
  github:
    identifier: weaviate/weaviate
    strip-prefix: v
    tag-filter: v
    use-tag: true
