package:
  name: xmlto
  version: 0.0.28
  epoch: 4
  description: Convert xml to many other formats
  copyright:
    - license: GPL-2.0-or-later
  dependencies:
    runtime:
      - bash
      - libxslt
      - perl-test-pod
      - perl-yaml-syck

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - docbook-xml
      - libxslt
      - perl-test-pod
      - perl-yaml-syck

pipeline:
  - uses: fetch
    with:
      expected-sha256: 1130df3a7957eb9f6f0d29e4aa1c75732a7dfb6d639be013859b5c7ec5421276
      uri: https://releases.pagure.org/xmlto/xmlto-${{package.version}}.tar.bz2

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: xmlto-doc
    pipeline:
      - uses: split/manpages
    description: xmlto manpages

update:
  enabled: true
  release-monitor:
    identifier: 13307
