package:
  name: yazi
  version: 0.3.0
  epoch: 0
  description: Blazing fast terminal file manager written in Rust, based on async I/O.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - file

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sxyazi/yazi
      tag: v${{package.version}}
      expected-commit: 7a380c2f0fdaec87992836e21dc8b6cd251af980

  - runs: |
      cargo auditable build --release

      install -Dm755 ./target/release/yazi "${{targets.destdir}}"/usr/bin/yazi

  - uses: strip

update:
  enabled: true
  github:
    identifier: sxyazi/yazi
    strip-prefix: v

test:
  pipeline:
    - runs: |
        yazi --version
