package:
  name: yq
  version: 4.44.2
  epoch: 1
  description: "yq is a portable command-line YAML, JSON, XML, CSV and properties processor"
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/mikefarah/yq
      tag: v${{package.version}}
      expected-commit: f15500b20a1c991c8729870ba60a4dc3524b6a94

  - uses: go/build
    with:
      packages: .
      output: yq

  - runs: |
      ${{targets.destdir}}/usr/bin/yq --version | grep "version v${{package.version}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: mikefarah/yq
    strip-prefix: v
