package:
  name: zarf
  version: 0.37.0
  epoch: 1
  description: DevSecOps for Air Gap & Limited-Connection Systems.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - busybox
      - ca-certificates-bundle
      - go
      - nodejs

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 1b95916005d4547cbd6b76bc2d3437a88eae3a73
      repository: https://github.com/zarf-dev/zarf
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/sigstore/cosign/v2@v2.2.4 google.golang.org/grpc@v1.64.1
      replaces: github.com/prometheus/common=github.com/prometheus/common@v0.45.0 github.com/prometheus/client_golang=github.com/prometheus/client_golang@v1.18.0 github.com/mholt/archiver/v3=github.com/anchore/archiver/v3@v3.5.2
      show-diff: true

  - uses: go/build
    with:
      ldflags: -s -w -X 'github.com/zarf-dev/zarf/src/config.CLIVersion=v${{package.version}}'
      output: zarf
      packages: .

  - uses: strip

test:
  pipeline:
    - runs: |
        zarf version || grep ${{package.version}}

update:
  enabled: true
  github:
    identifier: defenseunicorns/zarf
    strip-prefix: v
