package:
  name: zola
  version: 0.19.1 # The next time we update, see if the cherry-picked patch can be removed now.
  epoch: 1
  description: "A fast static site generator in a single binary with everything built-in"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - rust
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/getzola/zola
      expected-commit: 041da029eedbca30c195bc9cd8c1acf89b4f60c0
      tag: v${{package.version}}

  - name: Configure and build
    runs: |
      cargo auditable build --release
      mkdir -p ${{targets.destdir}}/usr/bin/
      mv target/release/zola ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: getzola/zola
    use-tag: true
    strip-prefix: v
