name: Build and install python package with pip

inputs:
  python:
    description: which python to use
    required: true
  dest:
    description: the destination
    default: ${{targets.subpkgdir}}

pipeline:
  - name: "pip build ${{inputs.python}}"
    runs: |
      export SOURCE_DATE_EPOCH=315532800
      py=${{inputs.python}}
      pyver=$("$py" -c 'import sys; print("%s.%s" % (sys.version_info.major, sys.version_info.minor))')
      sitepkgd=$("$py" -c 'import site; print(site.getsitepackages()[0])')
      sitepkgd=${sitepkgd#/}
      root=${{inputs.dest}}
      wd="./.wheels/$pyver"
      vr() { echo "execute:" "$@"; "$@"; }

      tmpd=$(mktemp -d)
      trap "rm -Rf '$tmpd'" EXIT

      # --find-links to an empty dir and --no-index makes pip fully "offline"
      distwheelsd="$tmpd/dist-wheels"
      mkdir -p "$distwheelsd"
      echo "$py is $pyver with site_packages dir '$sitepkgd'"
      vr $py -m pip wheel --verbose "--wheel-dir=$wd" \
          "--find-links=$distwheelsd" --no-index --no-build-isolation --no-deps .
      vr $py -m pip install --verbose \
          "--find-links=$distwheelsd" --no-index --no-build-isolation --no-deps \
          --force-reinstall --no-compile --prefix=/usr "--root=$root" "$wd"/*.whl
      vr $py -m compileall --invalidation-mode=unchecked-hash -r100 "$root/$sitepkgd"
