name: Bump rust deps to a certain version

# Leave go off here, some packages pin to an older version. Let's just assume this gets injected elsewhere.
needs:
  packages:
    - git
    - cargobump

inputs:
  cargoroot:
    description: The root of the cargo lock file
    default: .
  bump-file:
    description: |
      Patches file to use for updating the Cargo lock file
    default: ./cargobump-deps.yaml
  packages:
    description: |
      Packages to be used for updating the Cargo lock file via command line flag    

pipeline:
  - runs: |
      set -x
      cd "${{inputs.cargoroot}}"
      
      BUMP_FILE_FLAG=""
      PACKAGES_FLAG=""

      if [ -n "${{inputs.packages}}" ]; then
        PACKAGES_FLAG="--packages ${{inputs.packages}}"
      elif [ -f "${{inputs.bump-file}}" ]; then
        BUMP_FILE_FLAG="--bump-file ${{inputs.bump-file}}"
      fi

      cargobump $PACKAGES_FLAG $BUMP_FILE_FLAG
