issuer: https://accounts.google.com

# kleung:  ebuild-py5wka7s7g5no2hg8tpoqi9@kleung-chainguard.iam.gserviceaccount.com
# staging: build-uxu452jfbry53u7cw8s177l2@staging-enforce-cd1e.iam.gserviceaccount.com
# prod:    TBD
# "([kleung]|[staging]|[prod])"
subject_pattern: "(108286754379380263406|115259752302127378690)"

# Just cloning repo.
permissions:
  contents: read
  checks: write
