issuer: https://accounts.google.com

# staging-images: not in use
# prod-images: bot-logs@prod-images-c6e5.iam.gserviceaccount.com
subject: "112078453324641556493"

permissions:
  contents: read
  actions: read
  checks: read
  pull_requests: write
